/**
 * Committed public API baseline for @kern-ui/angular/addon-grid.
 *
 * Generated by tools/verify-kern-api-baseline.mjs. Update intentionally with
 * `npm run api:baseline:write` and review the declaration diff.
 */

import * as _angular_core from '@angular/core';
import { TemplateRef, AfterViewChecked, Signal } from '@angular/core';
import { KrnDataGridTranslations } from '@kern-ui/angular/core';

type KrnDataRowKey = string | number;
type KrnDataSortDirection = 'asc' | 'desc';
type KrnDataColumnPin = 'start' | 'end';
interface KrnDataCellContext<T> {
  readonly $implicit: unknown;
  readonly value: unknown;
  readonly row: T;
  readonly column: KrnDataColumn<T>;
  readonly rowIndex: number;
}
interface KrnDataHeaderContext<T> {
  readonly $implicit: KrnDataColumn<T>;
  readonly column: KrnDataColumn<T>;
  readonly columnIndex: number;
}
interface KrnDataRowContext<T> {
  readonly $implicit: T;
  readonly row: T;
  readonly rowIndex: number;
}
interface KrnDataColumnOptions<T, V = unknown> {
  readonly label: string;
  readonly sortable?: boolean;
  readonly width?: number;
  readonly minWidth?: number;
  readonly maxWidth?: number;
  readonly align?: 'start' | 'center' | 'end';
  readonly priority?: 'primary' | 'secondary' | 'tertiary';
  /**
   * Keeps the column at the logical start or end edge while the grid scrolls horizontally.
   *
   * Pinned columns are partitioned around unpinned columns without mutating the supplied array.
   * Logical edges make the same configuration work in both LTR and RTL documents.
   */
  readonly pinned?: KrnDataColumnPin;
  readonly sortValue?: (row: T) => unknown;
  readonly filterValue?: (row: T) => unknown;
  readonly compare?: (left: unknown, right: unknown, leftRow: T, rightRow: T) => number;
  readonly format?: (value: V, row: T) => string;
  readonly cellTemplate?: TemplateRef<KrnDataCellContext<T>>;
  readonly headerTemplate?: TemplateRef<KrnDataHeaderContext<T>>;
}
type KrnDataPropertyColumn<T> = T extends object
  ? {
      [K in Extract<keyof T, string>]: KrnDataColumnOptions<T, T[K]> & {
        /** Property key used as the stable column identifier and default accessor. */
        readonly key: K;
        readonly accessor?: undefined;
      };
    }[Extract<keyof T, string>]
  : never;
type KrnDataComputedColumn<T> = KrnDataColumnOptions<T, unknown> & {
  /** Stable identifier and value accessor for a computed column. */
  readonly key: string;
  readonly accessor: (row: T) => unknown;
};
type KrnDataColumn<T> = KrnDataPropertyColumn<T> | KrnDataComputedColumn<T>;
interface KrnDataGridClientMode {
  readonly kind: 'client';
  readonly pagination?: boolean;
}
interface KrnDataGridControlledMode {
  readonly kind: 'controlled';
  readonly totalRows: number;
}
/**
 * Fixed-height virtualization supports the same selection, sorting, filtering, and resize
 * contracts as the client grid. Row expansion is intentionally unsupported and is enforced at
 * runtime because `expandable` is a separate component input.
 */
interface KrnDataGridVirtualMode {
  readonly kind: 'virtual';
}
type KrnDataGridMode = KrnDataGridClientMode | KrnDataGridControlledMode | KrnDataGridVirtualMode;
interface KrnDataGridQuery {
  readonly filter: string;
  readonly page: number;
  readonly pageSize: number;
  readonly sortKey: string;
  readonly sortDirection: KrnDataSortDirection;
}
type KrnDataFilterPredicate<T> = (
  row: T,
  query: string,
  columns: readonly KrnDataColumn<T>[],
) => boolean;
interface KrnDataGridCellPosition {
  readonly row: number;
  readonly column: number;
}
interface KrnDataRowOccurrence<T> {
  readonly row: T;
  readonly key: KrnDataRowKey;
  readonly sourceIndex: number;
}
declare class KrnDataGrid<T> implements AfterViewChecked {
  private readonly host;
  private readonly destroyRef;
  private readonly platform;
  private readonly locale;
  private readonly translations;
  private readonly collator;
  private readonly viewport;
  private virtualFocusSubscription;
  private virtualRowResizeObserver;
  private observedVirtualRow;
  private readonly measuredVirtualRowHeight;
  private columnResizeObserver;
  private readonly observedColumnHeaders;
  private readonly measuredColumnWidths;
  private readonly managedTabIndexes;
  private readonly effectiveMode;
  private readonly sourceRows;
  private readonly validatedColumns;
  readonly data: _angular_core.InputSignal<readonly T[]>;
  readonly columns: _angular_core.InputSignal<readonly KrnDataColumn<T>[]>;
  readonly rowIdentity: _angular_core.InputSignal<(row: T, index: number) => KrnDataRowKey>;
  readonly mode: _angular_core.InputSignal<KrnDataGridMode | null>;
  readonly labels: _angular_core.InputSignal<Partial<KrnDataGridTranslations>>;
  readonly ariaLabel: _angular_core.InputSignal<string>;
  readonly loading: _angular_core.InputSignalWithTransform<boolean, unknown>;
  readonly error: _angular_core.InputSignal<string>;
  readonly emptyLabel: _angular_core.InputSignal<string>;
  readonly filterable: _angular_core.InputSignalWithTransform<boolean, unknown>;
  readonly filterPlaceholder: _angular_core.InputSignal<string>;
  readonly filterPredicate: _angular_core.InputSignal<KrnDataFilterPredicate<T> | null>;
  readonly selectable: _angular_core.InputSignalWithTransform<boolean, unknown>;
  readonly expandable: _angular_core.InputSignalWithTransform<boolean, unknown>;
  readonly expandedContent: _angular_core.InputSignal<(row: T) => string>;
  readonly expandedTemplate: _angular_core.InputSignal<TemplateRef<KrnDataRowContext<T>> | null>;
  readonly defaultCellTemplate: _angular_core.InputSignal<TemplateRef<
    KrnDataCellContext<T>
  > | null>;
  readonly defaultHeaderTemplate: _angular_core.InputSignal<TemplateRef<
    KrnDataHeaderContext<T>
  > | null>;
  readonly resizable: _angular_core.InputSignalWithTransform<boolean, unknown>;
  /** @deprecated Prefer the discriminated `mode` input. */
  readonly pagination: _angular_core.InputSignalWithTransform<boolean, unknown>;
  readonly compact: _angular_core.InputSignalWithTransform<boolean, unknown>;
  /** @deprecated Prefer `{ kind: 'virtual' }` through the `mode` input. */
  readonly virtualize: _angular_core.InputSignalWithTransform<boolean, unknown>;
  readonly viewportHeight: _angular_core.InputSignalWithTransform<number, unknown>;
  readonly pageSize: _angular_core.InputSignalWithTransform<number, unknown>;
  readonly columnChooser: _angular_core.InputSignalWithTransform<boolean, unknown>;
  protected readonly copy: _angular_core.Signal<{
    ariaLabel: string;
    empty: string;
    filterPlaceholder: string;
    columns: string;
    errorTitle: string;
    loading: string;
    clearFilter: string;
    selectAllVisible: string;
    selectAllPage: string;
    scrollRegion: string;
    expand: string;
    expandRow: string;
    collapseRow: string;
    pagination: string;
    previousPage: string;
    nextPage: string;
    rowCount: (count: number) => string;
    filterLabel: (label: string) => string;
    selectRow: (index: number) => string;
    resizeColumn: (label: string) => string;
    widthInPixels: (width: number) => string;
    pageRange: (start: number, end: number, total: number) => string;
  }>;
  readonly filter: _angular_core.ModelSignal<string>;
  readonly page: _angular_core.ModelSignal<number>;
  readonly selected: _angular_core.ModelSignal<ReadonlySet<KrnDataRowKey>>;
  readonly expanded: _angular_core.ModelSignal<ReadonlySet<KrnDataRowKey>>;
  readonly hiddenColumnKeys: _angular_core.ModelSignal<ReadonlySet<string>>;
  readonly sortKey: _angular_core.ModelSignal<string>;
  readonly sortDirection: _angular_core.ModelSignal<KrnDataSortDirection>;
  readonly queryChange: _angular_core.OutputEmitterRef<KrnDataGridQuery>;
  protected readonly activeCell: _angular_core.WritableSignal<KrnDataGridCellPosition>;
  protected readonly actionCell: _angular_core.WritableSignal<KrnDataGridCellPosition | null>;
  protected readonly widths: _angular_core.WritableSignal<Readonly<Record<string, number>>>;
  protected readonly rowHeight: _angular_core.Signal<number>;
  protected readonly normalizedViewportHeight: _angular_core.Signal<number>;
  protected readonly normalizedPageSize: _angular_core.Signal<number>;
  protected readonly isVirtual: _angular_core.Signal<boolean>;
  protected readonly isControlled: _angular_core.Signal<boolean>;
  protected readonly usesPagination: _angular_core.Signal<boolean>;
  private readonly normalizedHiddenColumnKeys;
  protected readonly visibleColumns: _angular_core.Signal<KrnDataColumn<T>[]>;
  protected readonly hasPinnedStartColumns: _angular_core.Signal<boolean>;
  private readonly pinnedBoundaryKeys;
  private readonly pinnedColumnOffsets;
  protected readonly dataColumnOffset: _angular_core.Signal<number>;
  protected readonly gridColumnCount: _angular_core.Signal<number>;
  protected readonly processed: _angular_core.Signal<KrnDataRowOccurrence<T>[]>;
  private normalizeForSearch;
  protected readonly totalRowCount: _angular_core.Signal<number>;
  protected readonly pageCount: _angular_core.Signal<number>;
  protected readonly currentPage: _angular_core.Signal<number>;
  protected readonly rowOffset: _angular_core.Signal<number>;
  protected readonly pageRows: _angular_core.Signal<KrnDataRowOccurrence<T>[]>;
  protected readonly visibleRows: _angular_core.Signal<KrnDataRowOccurrence<T>[]>;
  protected readonly focusCellPosition: _angular_core.Signal<{
    row: number;
    column: number;
  }>;
  protected readonly pageStart: _angular_core.Signal<number>;
  protected readonly pageEnd: _angular_core.Signal<number>;
  protected readonly allVisibleSelected: _angular_core.Signal<boolean>;
  protected readonly someVisibleSelected: _angular_core.Signal<boolean>;
  protected readonly loadingRows: number[];
  protected readonly trackRow: (
    _index: number,
    occurrence: KrnDataRowOccurrence<T>,
  ) => KrnDataRowKey;
  private resizeState;
  constructor();
  ngAfterViewChecked(): void;
  protected value(row: T, column: KrnDataColumn<T>): unknown;
  protected cellText(row: T, column: KrnDataColumn<T>): string;
  protected columnLabel(column: KrnDataColumn<T>): string;
  protected resolveCellTemplate(
    column: KrnDataColumn<T>,
  ): TemplateRef<KrnDataCellContext<T>> | null;
  protected resolveHeaderTemplate(
    column: KrnDataColumn<T>,
  ): TemplateRef<KrnDataHeaderContext<T>> | null;
  protected cellContext(row: T, column: KrnDataColumn<T>, rowIndex: number): KrnDataCellContext<T>;
  protected headerContext(column: KrnDataColumn<T>, columnIndex: number): KrnDataHeaderContext<T>;
  protected rowContext(row: T, rowIndex: number): KrnDataRowContext<T>;
  protected setFilter(event: Event): void;
  protected clearFilter(): void;
  protected sort(column: KrnDataColumn<T>): void;
  protected goToPage(page: number): void;
  protected ariaSort(column: KrnDataColumn<T>): 'ascending' | 'descending' | 'none' | null;
  protected sortMark(column: KrnDataColumn<T>): string;
  protected isSelected(occurrence: KrnDataRowOccurrence<T>): boolean;
  protected toggleRow(occurrence: KrnDataRowOccurrence<T>): void;
  protected toggleAllVisible(): void;
  protected isExpanded(occurrence: KrnDataRowOccurrence<T>): boolean;
  protected toggleExpanded(occurrence: KrnDataRowOccurrence<T>): void;
  protected isColumnVisible(key: string): boolean;
  protected setColumnVisible(key: string, event: Event): void;
  protected columnWidth(column: KrnDataColumn<T>): number;
  protected columnMinWidth(column: KrnDataColumn<T>): number;
  protected columnMaxWidth(column: KrnDataColumn<T>): number;
  private pinnedColumnWidth;
  protected utilityColumnOffset(index: number): string;
  protected columnPinnedStart(column: KrnDataColumn<T>): string | null;
  protected columnPinnedEnd(column: KrnDataColumn<T>): string | null;
  protected columnPinBoundary(column: KrnDataColumn<T>): KrnDataColumnPin | null;
  protected startResize(event: PointerEvent, column: KrnDataColumn<T>): void;
  protected resize(event: PointerEvent, column: KrnDataColumn<T>): void;
  protected endResize(event: PointerEvent): void;
  protected resizeWithKeyboard(event: KeyboardEvent, column: KrnDataColumn<T>): void;
  protected isActionCell(row: number, column: number): boolean;
  protected onCellFocusIn(event: FocusEvent, row: number, column: number): void;
  protected onCellPointerDown(event: PointerEvent, row: number, column: number): void;
  protected onGridFocusOut(event: FocusEvent): void;
  protected onCellKeydown(
    event: KeyboardEvent,
    row: number,
    column: number,
    rowCount: number,
  ): void;
  private onActionKeydown;
  private enterActionMode;
  private exitActionMode;
  private syncManagedTabStops;
  private actionableDescendants;
  private findActionTarget;
  private setManagedTabIndex;
  private restoreManagedTabIndexes;
  private restoreTabIndex;
  private syncPinnedColumnMeasurements;
  private measurePinnedColumnHeaders;
  private syncVirtualRowMeasurement;
  private measureVirtualRow;
  private eventCell;
  private cellPosition;
  private asHTMLElement;
  private asElement;
  private focusCell;
  private emitQuery;
  private setColumnWidth;
  private isRtl;
  private positiveInteger;
  private toggleSet;
  static ɵfac: _angular_core.ɵɵFactoryDeclaration<KrnDataGrid<any>, never>;
  static ɵcmp: _angular_core.ɵɵComponentDeclaration<
    KrnDataGrid<any>,
    'krn-data-grid, krn-data-table',
    never,
    {
      data: { alias: 'data'; required: true; isSignal: true };
      columns: { alias: 'columns'; required: true; isSignal: true };
      rowIdentity: { alias: 'rowIdentity'; required: true; isSignal: true };
      mode: { alias: 'mode'; required: false; isSignal: true };
      labels: { alias: 'labels'; required: false; isSignal: true };
      ariaLabel: { alias: 'ariaLabel'; required: false; isSignal: true };
      loading: { alias: 'loading'; required: false; isSignal: true };
      error: { alias: 'error'; required: false; isSignal: true };
      emptyLabel: { alias: 'emptyLabel'; required: false; isSignal: true };
      filterable: { alias: 'filterable'; required: false; isSignal: true };
      filterPlaceholder: { alias: 'filterPlaceholder'; required: false; isSignal: true };
      filterPredicate: { alias: 'filterPredicate'; required: false; isSignal: true };
      selectable: { alias: 'selectable'; required: false; isSignal: true };
      expandable: { alias: 'expandable'; required: false; isSignal: true };
      expandedContent: { alias: 'expandedContent'; required: false; isSignal: true };
      expandedTemplate: { alias: 'expandedTemplate'; required: false; isSignal: true };
      defaultCellTemplate: { alias: 'defaultCellTemplate'; required: false; isSignal: true };
      defaultHeaderTemplate: { alias: 'defaultHeaderTemplate'; required: false; isSignal: true };
      resizable: { alias: 'resizable'; required: false; isSignal: true };
      pagination: { alias: 'pagination'; required: false; isSignal: true };
      compact: { alias: 'compact'; required: false; isSignal: true };
      virtualize: { alias: 'virtualize'; required: false; isSignal: true };
      viewportHeight: { alias: 'viewportHeight'; required: false; isSignal: true };
      pageSize: { alias: 'pageSize'; required: false; isSignal: true };
      columnChooser: { alias: 'columnChooser'; required: false; isSignal: true };
      filter: { alias: 'filter'; required: false; isSignal: true };
      page: { alias: 'page'; required: false; isSignal: true };
      selected: { alias: 'selected'; required: false; isSignal: true };
      expanded: { alias: 'expanded'; required: false; isSignal: true };
      hiddenColumnKeys: { alias: 'hiddenColumnKeys'; required: false; isSignal: true };
      sortKey: { alias: 'sortKey'; required: false; isSignal: true };
      sortDirection: { alias: 'sortDirection'; required: false; isSignal: true };
    },
    {
      filter: 'filterChange';
      page: 'pageChange';
      selected: 'selectedChange';
      expanded: 'expandedChange';
      hiddenColumnKeys: 'hiddenColumnKeysChange';
      sortKey: 'sortKeyChange';
      sortDirection: 'sortDirectionChange';
      queryChange: 'queryChange';
    },
    never,
    never,
    true,
    never
  >;
}

interface KrnDataGridPage<T> {
  readonly data: readonly T[];
  readonly totalRows: number;
}
interface KrnDataGridLoadContext {
  /** Aborted whenever a newer query starts or the source is disconnected. */
  readonly signal: AbortSignal;
}
type KrnDataGridLoader<T> = (
  query: Readonly<KrnDataGridQuery>,
  context: KrnDataGridLoadContext,
) => Promise<KrnDataGridPage<T>>;
interface KrnDataGridDataSourceOptions<T> {
  readonly initialPage?: KrnDataGridPage<T>;
  readonly errorMessage?: (error: unknown) => string;
}
/**
 * Latest-query-wins adapter for the Data Grid controlled mode.
 *
 * The adapter deliberately owns request state, not transport policy: consumers can use fetch,
 * GraphQL, RPC, or a repository in the loader. Aborted requests never overwrite newer data.
 */
declare class KrnDataGridDataSource<T> {
  private readonly loader;
  private readonly dataState;
  private readonly totalRowsState;
  private readonly loadingState;
  private readonly errorState;
  private readonly queryState;
  private readonly errorMessage;
  private activeController;
  private requestSequence;
  readonly data: Signal<readonly T[]>;
  readonly totalRows: Signal<number>;
  readonly loading: Signal<boolean>;
  readonly error: Signal<string | null>;
  readonly query: Signal<Readonly<KrnDataGridQuery> | null>;
  constructor(loader: KrnDataGridLoader<T>, options?: KrnDataGridDataSourceOptions<T>);
  load(query: Readonly<KrnDataGridQuery>): Promise<KrnDataGridPage<T> | null>;
  reload(): Promise<KrnDataGridPage<T> | null>;
  reset(page?: KrnDataGridPage<T>): void;
  disconnect(): void;
  private assertPage;
}

export { KrnDataGrid, KrnDataGridDataSource, KrnDataGrid as KrnDataTable };
export type {
  KrnDataCellContext,
  KrnDataColumn,
  KrnDataColumnOptions,
  KrnDataColumnPin,
  KrnDataComputedColumn,
  KrnDataFilterPredicate,
  KrnDataGridClientMode,
  KrnDataGridControlledMode,
  KrnDataGridDataSourceOptions,
  KrnDataGridLoadContext,
  KrnDataGridLoader,
  KrnDataGridMode,
  KrnDataGridPage,
  KrnDataGridQuery,
  KrnDataGridVirtualMode,
  KrnDataHeaderContext,
  KrnDataPropertyColumn,
  KrnDataRowContext,
  KrnDataRowKey,
  KrnDataSortDirection,
};
