/**
 * Committed public API baseline for @kern-ui/angular/addon-charts.
 *
 * Generated by tools/verify-kern-api-baseline.mjs. Update intentionally with
 * `npm run api:baseline:write` and review the declaration diff.
 */

import * as _angular_core from '@angular/core';

interface KrnChartDatum {
  readonly label: string;
  readonly value: number;
  readonly description?: string;
}
type KrnChartType = 'line' | 'bar' | 'donut';
interface KrnChartLabels {
  readonly viewData: string;
  readonly hideData: string;
  readonly total: string;
  readonly sourceData: string;
  readonly labelColumn: string;
  readonly valueColumn: string;
  readonly shareColumn: string;
  readonly legend: string;
  readonly percentOfTotal: string;
  readonly datumLabel: (label: string, value: string) => string;
  readonly datumShareLabel: (label: string, value: string, share: string) => string;
  readonly sourceDataCaption: (title: string, sourceData: string) => string;
  readonly summary: (title: string, items: readonly string[]) => string;
}
type KrnChartValueFormatter = (value: number) => string;
interface KrnLinePoint extends KrnChartDatum {
  readonly x: number;
  readonly y: number;
}
interface KrnDonutSegment extends KrnChartDatum {
  readonly percent: number;
  readonly dashPercent: number;
  readonly offset: number;
  readonly targetX: number;
  readonly targetY: number;
}
interface KrnTooltipPosition {
  readonly x: number;
  readonly y: number;
}
declare class KrnChart {
  private readonly destroyRef;
  private readonly platform;
  private readonly translations;
  private readonly host;
  private hideTimer;
  protected readonly Math: Math;
  protected readonly gridLines: number[];
  protected readonly toggle: (value: boolean) => boolean;
  readonly type: _angular_core.InputSignal<KrnChartType>;
  readonly title: _angular_core.InputSignal<string>;
  readonly eyebrow: _angular_core.InputSignal<string>;
  readonly description: _angular_core.InputSignal<string>;
  readonly data: _angular_core.InputSignal<readonly KrnChartDatum[]>;
  readonly locale: _angular_core.InputSignal<string | string[]>;
  readonly labels: _angular_core.InputSignal<Partial<KrnChartLabels>>;
  readonly valueFormatter: _angular_core.InputSignal<KrnChartValueFormatter | null>;
  readonly percentFormatter: _angular_core.InputSignal<KrnChartValueFormatter | null>;
  readonly tableVisible: _angular_core.ModelSignal<boolean>;
  readonly activeIndex: _angular_core.ModelSignal<number | null>;
  readonly palette: _angular_core.InputSignal<readonly string[]>;
  protected readonly resolvedLabels: _angular_core.Signal<KrnChartLabels>;
  private readonly numberFormatter;
  private readonly percentageNumberFormatter;
  protected readonly total: _angular_core.Signal<number>;
  private readonly maxValue;
  protected readonly linePoints: _angular_core.Signal<readonly KrnLinePoint[]>;
  protected readonly linePath: _angular_core.Signal<string>;
  protected readonly areaPath: _angular_core.Signal<string>;
  protected readonly bars: _angular_core.Signal<
    {
      x: number;
      y: number;
      width: number;
      height: number;
      label: string;
      value: number;
      description?: string;
    }[]
  >;
  protected readonly donutSegments: _angular_core.Signal<readonly KrnDonutSegment[]>;
  protected readonly activeDatum: _angular_core.Signal<KrnChartDatum | null>;
  protected readonly tooltipPosition: _angular_core.Signal<KrnTooltipPosition>;
  protected readonly accessibleSummary: _angular_core.Signal<string>;
  constructor();
  protected color(index: number): string;
  protected barOpacity(index: number): number;
  protected setActive(index: number): void;
  protected clearActive(index: number): void;
  protected markTabIndex(index: number): 0 | -1;
  protected onMarkKeydown(event: KeyboardEvent, index: number): void;
  protected accessibleDatumLabel(datum: KrnChartDatum): string;
  protected accessibleDatumShareLabel(datum: KrnDonutSegment): string;
  protected abbreviated(label: string): string;
  protected uppercase(label: string): string;
  protected formattedValue(value: number): string;
  protected formattedPercent(value: number): string;
  protected percentOfTotal(value: number): string;
  private cancelHideTimer;
  static ɵfac: _angular_core.ɵɵFactoryDeclaration<KrnChart, never>;
  static ɵcmp: _angular_core.ɵɵComponentDeclaration<
    KrnChart,
    'krn-chart',
    never,
    {
      type: { alias: 'type'; required: false; isSignal: true };
      title: { alias: 'title'; required: true; isSignal: true };
      eyebrow: { alias: 'eyebrow'; required: false; isSignal: true };
      description: { alias: 'description'; required: false; isSignal: true };
      data: { alias: 'data'; required: true; isSignal: true };
      locale: { alias: 'locale'; required: false; isSignal: true };
      labels: { alias: 'labels'; required: false; isSignal: true };
      valueFormatter: { alias: 'valueFormatter'; required: false; isSignal: true };
      percentFormatter: { alias: 'percentFormatter'; required: false; isSignal: true };
      tableVisible: { alias: 'tableVisible'; required: false; isSignal: true };
      activeIndex: { alias: 'activeIndex'; required: false; isSignal: true };
      palette: { alias: 'palette'; required: false; isSignal: true };
    },
    { tableVisible: 'tableVisibleChange'; activeIndex: 'activeIndexChange' },
    never,
    never,
    true,
    never
  >;
}
declare class KrnLineChart {
  readonly title: _angular_core.InputSignal<string>;
  readonly eyebrow: _angular_core.InputSignal<string>;
  readonly description: _angular_core.InputSignal<string>;
  readonly data: _angular_core.InputSignal<readonly KrnChartDatum[]>;
  readonly palette: _angular_core.InputSignal<readonly string[]>;
  readonly locale: _angular_core.InputSignal<string | string[]>;
  readonly labels: _angular_core.InputSignal<Partial<KrnChartLabels>>;
  readonly valueFormatter: _angular_core.InputSignal<KrnChartValueFormatter | null>;
  readonly percentFormatter: _angular_core.InputSignal<KrnChartValueFormatter | null>;
  static ɵfac: _angular_core.ɵɵFactoryDeclaration<KrnLineChart, never>;
  static ɵcmp: _angular_core.ɵɵComponentDeclaration<
    KrnLineChart,
    'krn-line-chart',
    never,
    {
      title: { alias: 'title'; required: true; isSignal: true };
      eyebrow: { alias: 'eyebrow'; required: false; isSignal: true };
      description: { alias: 'description'; required: false; isSignal: true };
      data: { alias: 'data'; required: true; isSignal: true };
      palette: { alias: 'palette'; required: false; isSignal: true };
      locale: { alias: 'locale'; required: false; isSignal: true };
      labels: { alias: 'labels'; required: false; isSignal: true };
      valueFormatter: { alias: 'valueFormatter'; required: false; isSignal: true };
      percentFormatter: { alias: 'percentFormatter'; required: false; isSignal: true };
    },
    {},
    never,
    never,
    true,
    never
  >;
}
declare class KrnBarChart {
  readonly title: _angular_core.InputSignal<string>;
  readonly eyebrow: _angular_core.InputSignal<string>;
  readonly description: _angular_core.InputSignal<string>;
  readonly data: _angular_core.InputSignal<readonly KrnChartDatum[]>;
  readonly palette: _angular_core.InputSignal<readonly string[]>;
  readonly locale: _angular_core.InputSignal<string | string[]>;
  readonly labels: _angular_core.InputSignal<Partial<KrnChartLabels>>;
  readonly valueFormatter: _angular_core.InputSignal<KrnChartValueFormatter | null>;
  readonly percentFormatter: _angular_core.InputSignal<KrnChartValueFormatter | null>;
  static ɵfac: _angular_core.ɵɵFactoryDeclaration<KrnBarChart, never>;
  static ɵcmp: _angular_core.ɵɵComponentDeclaration<
    KrnBarChart,
    'krn-bar-chart',
    never,
    {
      title: { alias: 'title'; required: true; isSignal: true };
      eyebrow: { alias: 'eyebrow'; required: false; isSignal: true };
      description: { alias: 'description'; required: false; isSignal: true };
      data: { alias: 'data'; required: true; isSignal: true };
      palette: { alias: 'palette'; required: false; isSignal: true };
      locale: { alias: 'locale'; required: false; isSignal: true };
      labels: { alias: 'labels'; required: false; isSignal: true };
      valueFormatter: { alias: 'valueFormatter'; required: false; isSignal: true };
      percentFormatter: { alias: 'percentFormatter'; required: false; isSignal: true };
    },
    {},
    never,
    never,
    true,
    never
  >;
}
declare class KrnDonutChart {
  readonly title: _angular_core.InputSignal<string>;
  readonly eyebrow: _angular_core.InputSignal<string>;
  readonly description: _angular_core.InputSignal<string>;
  readonly data: _angular_core.InputSignal<readonly KrnChartDatum[]>;
  readonly palette: _angular_core.InputSignal<readonly string[]>;
  readonly locale: _angular_core.InputSignal<string | string[]>;
  readonly labels: _angular_core.InputSignal<Partial<KrnChartLabels>>;
  readonly valueFormatter: _angular_core.InputSignal<KrnChartValueFormatter | null>;
  readonly percentFormatter: _angular_core.InputSignal<KrnChartValueFormatter | null>;
  static ɵfac: _angular_core.ɵɵFactoryDeclaration<KrnDonutChart, never>;
  static ɵcmp: _angular_core.ɵɵComponentDeclaration<
    KrnDonutChart,
    'krn-donut-chart',
    never,
    {
      title: { alias: 'title'; required: true; isSignal: true };
      eyebrow: { alias: 'eyebrow'; required: false; isSignal: true };
      description: { alias: 'description'; required: false; isSignal: true };
      data: { alias: 'data'; required: true; isSignal: true };
      palette: { alias: 'palette'; required: false; isSignal: true };
      locale: { alias: 'locale'; required: false; isSignal: true };
      labels: { alias: 'labels'; required: false; isSignal: true };
      valueFormatter: { alias: 'valueFormatter'; required: false; isSignal: true };
      percentFormatter: { alias: 'percentFormatter'; required: false; isSignal: true };
    },
    {},
    never,
    never,
    true,
    never
  >;
}

export { KrnBarChart, KrnChart, KrnDonutChart, KrnLineChart };
export type { KrnChartDatum, KrnChartLabels, KrnChartType, KrnChartValueFormatter };
