/**
 * Committed public API baseline for @kern-ui/angular/cdk.
 *
 * Generated by tools/verify-kern-api-baseline.mjs. Update intentionally with
 * `npm run api:baseline:write` and review the declaration diff.
 */

import * as i0 from '@angular/core';
import { TemplateRef, Type, InjectionToken, FactoryProvider } from '@angular/core';

/**
 * Document- and application-scoped, SSR-safe ID generation.
 *
 * `next` shares its counters across Angular roots and records server allocations
 * on the owning component host. Hydration consumes that local ledger, preserving
 * even base IDs that only appear through derived `tab-*` or `title-*` IDs when
 * roots hydrate out of order. `fromKey` remains order-independent.
 */
declare class KrnIdService {
  private readonly applicationId;
  private readonly platform;
  private readonly state;
  next(prefix?: string): string;
  fromKey(prefix: string, key: string | number): string;
  private currentHost;
  private claimHydratedId;
  private recordServerId;
  private reserveHydrationLedgers;
  private readLedger;
  private writeLedger;
  private sequentialCount;
  static ɵfac: i0.ɵɵFactoryDeclaration<KrnIdService, never>;
  static ɵprov: i0.ɵɵInjectableDeclaration<KrnIdService>;
}

/**
 * Content accepted by composable Kern APIs.
 *
 * Components should narrow this union deliberately and document which context
 * is passed to templates. Plain strings remain the preferred accessible default.
 */
type KrnContent<TContext = void, TComponent extends object = object> =
  string | TemplateRef<TContext> | Type<TComponent>;
/** Standard template context for item-based components such as Select or Grid. */
interface KrnItemContentContext<TItem, TMeta = undefined> {
  readonly $implicit: TItem;
  readonly item: TItem;
  readonly index: number;
  readonly meta: TMeta;
}
declare function isKrnTemplateContent<TContext>(
  content: KrnContent<TContext>,
): content is TemplateRef<TContext>;
declare function isKrnComponentContent<TComponent extends object>(
  content: KrnContent<unknown, TComponent>,
): content is Type<TComponent>;

/**
 * Creates a hierarchical immutable options contract.
 *
 * Defaults, inherited provider values, and provider patches must be plain
 * records at runtime: objects with the ordinary `Object.prototype` (including
 * cross-realm objects) or a null prototype. Arrays, functions, class instances,
 * and built-in collection or asynchronous objects are rejected rather than
 * silently losing their type. Only enumerable own data properties are accepted;
 * non-enumerable properties and accessors, including symbol properties, are
 * rejected without invoking getters.
 *
 * Providers merge their defined properties over the nearest parent scope.
 * Component instance inputs can then apply their own final overrides without
 * mutating the shared provider value.
 *
 * Immutability is deliberately shallow and top-level: each resolved record is
 * cloned and frozen, while nested values retain their original identities and
 * must be treated as immutable by their owners.
 *
 * This stable foundation is shared by component families that need immutable,
 * hierarchically scoped defaults without coupling their public option types.
 */
declare function createKrnOptions<T extends object>(
  description: string,
  defaults: T,
): readonly [
  InjectionToken<Readonly<T>>,
  (patch: Partial<T> | (() => Partial<T>)) => FactoryProvider,
];

/**
 * Replaceable boundary for writing plain text to the system clipboard.
 *
 * The default writer prefers the asynchronous Clipboard API and only uses the
 * Angular CDK fallback when that modern API is absent. Consumers can replace
 * this token in tests or constrained rendering environments.
 */
interface KrnClipboardWriter {
  writeText(value: string): Promise<void>;
}
/** Application-replaceable clipboard writer used by KERN copy affordances. */
declare const KRN_CLIPBOARD_WRITER: InjectionToken<KrnClipboardWriter>;

/** Resolves a versioned runtime channel shared by every Kern bundle on one document. */
declare function getKrnDocumentRuntimeChannel<T>(
  document: Document,
  channelKey: symbol,
  create: () => T,
): T;

type KrnScheduledHandle = ReturnType<typeof globalThis.setTimeout>;
/** Minimal browser CloseWatcher surface used without depending on lib.dom support. */
interface KrnCloseWatcher {
  addEventListener(type: 'cancel' | 'close', listener: EventListener): void;
  removeEventListener(type: 'cancel' | 'close', listener: EventListener): void;
  destroy(): void;
}
type KrnCloseWatcherFactory = () => KrnCloseWatcher | null;
/**
 * The browser capabilities Kern uses at runtime.
 *
 * Components should inject this contract instead of reading global `window`,
 * `document`, storage, or media-query APIs directly. Tests and non-browser
 * renderers can replace it through `provideKern`.
 */
interface KrnPlatformAdapter {
  readonly document: Document;
  readonly isBrowser: boolean;
  readonly window: (Window & typeof globalThis) | null;
  readonly localStorage: Storage | null;
  /** Creates a native close-request source, or returns null when unsupported. */
  readonly createCloseWatcher?: KrnCloseWatcherFactory;
  matchMedia(query: string): MediaQueryList | null;
  requestAnimationFrame(callback: FrameRequestCallback): number | null;
  cancelAnimationFrame(handle: number | null): void;
  schedule(callback: () => void, delay?: number): KrnScheduledHandle | null;
  cancelScheduled(handle: KrnScheduledHandle | null): void;
  queueMicrotask(callback: () => void): void;
  now(): number;
}
declare function krnIsNode(platform: KrnPlatformAdapter, value: unknown): value is Node;
declare function krnIsElement(platform: KrnPlatformAdapter, value: unknown): value is Element;
declare function krnIsHtmlElement(
  platform: KrnPlatformAdapter,
  value: unknown,
): value is HTMLElement;
declare function krnIsInputElement(
  platform: KrnPlatformAdapter,
  value: unknown,
): value is HTMLInputElement;
/**
 * Resolves Kern's effective motion preference.
 *
 * The explicit application preference wins over the operating-system media
 * query. Server renderers return `true` so animation-dependent teardown never
 * delays deterministic rendering.
 */
declare function krnPrefersReducedMotion(platform: KrnPlatformAdapter): boolean;
/** Replaceable platform boundary used by all new low-level Kern services. */
declare const KRN_PLATFORM: InjectionToken<KrnPlatformAdapter>;
/** Resolves the element where application-level overlay portals are attached. */
type KrnOverlayHostResolver = () => HTMLElement | null;
declare const KRN_OVERLAY_HOST: InjectionToken<KrnOverlayHostResolver>;

type KrnOverlayInitialFocus = 'first-tabbable' | 'surface' | string;
/**
 * Injector-scoped facade over the modal coordinator shared by one `Document`.
 *
 * Multiple Angular roots therefore share one stack, one close watcher, one
 * scroll lock and one background state, while identical local overlay IDs stay
 * isolated by the facade lease.
 */
declare class KrnOverlayCoordinator {
  #private;
  constructor();
  activate(
    id: string,
    host?: HTMLElement | null,
    restoreFocus?: HTMLElement | false | null,
    closeRequest?: (() => void) | null,
  ): void;
  deactivate(id: string, focusRestoreDelay?: number, shouldRestoreFocus?: boolean): void;
  /** Updates close behavior without changing the overlay's position in the active stack. */
  updateCloseRequest(id: string, closeRequest: (() => void) | null): void;
  isTop(id: string): boolean;
  /**
   * Associates a CDK overlay branch with the element that opened it.
   *
   * Kern components call this after attachment. Custom overlay primitives that use the
   * `krn-overlay-pane` marker must register too, otherwise a modal treats their branch as
   * unrelated background content.
   */
  registerOverlayOwnership(
    origin: HTMLElement,
    pane: HTMLElement,
    backdrop?: HTMLElement | null,
  ): void;
  /**
   * Returns whether an event/focus target belongs to an overlay opened from
   * `owner`, including recursively nested overlay branches.
   *
   * This is the active-zone boundary used by non-modal connected overlays:
   * moving focus or a pointer into a child dropdown must not close its parent.
   */
  isOwnedBy(owner: HTMLElement, target: EventTarget | null): boolean;
  focusInitial(panel: HTMLElement, initialFocus: KrnOverlayInitialFocus): void;
  static ɵfac: i0.ɵɵFactoryDeclaration<KrnOverlayCoordinator, never>;
  static ɵprov: i0.ɵɵInjectableDeclaration<KrnOverlayCoordinator>;
}

export {
  KRN_CLIPBOARD_WRITER,
  KRN_OVERLAY_HOST,
  KRN_PLATFORM,
  KrnIdService,
  KrnOverlayCoordinator,
  createKrnOptions,
  isKrnComponentContent,
  isKrnTemplateContent,
  krnIsElement,
  krnIsHtmlElement,
  krnIsInputElement,
  krnIsNode,
  krnPrefersReducedMotion,
  getKrnDocumentRuntimeChannel as ɵgetKrnDocumentRuntimeChannel,
};
export type {
  KrnClipboardWriter,
  KrnCloseWatcher,
  KrnCloseWatcherFactory,
  KrnContent,
  KrnItemContentContext,
  KrnOverlayHostResolver,
  KrnOverlayInitialFocus,
  KrnPlatformAdapter,
  KrnScheduledHandle,
};
