/**
 * Committed public API baseline for @kern-ui/angular/cdk.
 *
 * Generated by tools/verify-kern-api-baseline.mjs. Update intentionally with
 * `npm run api:baseline:write` and review the declaration diff.
 */

import * as i0 from '@angular/core';
import { TemplateRef, Type, InjectionToken, FactoryProvider } from '@angular/core';

/**
 * Application-scoped, SSR-safe ID generation.
 *
 * `next` is appropriate when server and client instantiate the same view tree
 * in the same order. `fromKey` is order-independent and should be preferred for
 * data-driven content with a stable application key.
 */
declare class KrnIdService {
  private readonly applicationId;
  private readonly counters;
  next(prefix?: string): string;
  fromKey(prefix: string, key: string | number): string;
  static ɵfac: i0.ɵɵFactoryDeclaration<KrnIdService, never>;
  static ɵprov: i0.ɵɵInjectableDeclaration<KrnIdService>;
}

/**
 * Content accepted by composable Kern APIs.
 *
 * Components should narrow this union deliberately and document which context
 * is passed to templates. Plain strings remain the preferred accessible default.
 */
type KrnContent<TContext = void, TComponent extends object = object> =
  string | TemplateRef<TContext> | Type<TComponent>;
/** Standard template context for item-based components such as Select or Grid. */
interface KrnItemContentContext<TItem, TMeta = undefined> {
  readonly $implicit: TItem;
  readonly item: TItem;
  readonly index: number;
  readonly meta: TMeta;
}
declare function isKrnTemplateContent<TContext>(
  content: KrnContent<TContext>,
): content is TemplateRef<TContext>;
declare function isKrnComponentContent<TComponent extends object>(
  content: KrnContent<unknown, TComponent>,
): content is Type<TComponent>;

/**
 * Creates a hierarchical immutable options contract.
 *
 * Defaults, inherited provider values, and provider patches must be plain
 * records at runtime: objects with the ordinary `Object.prototype` (including
 * cross-realm objects) or a null prototype. Arrays, functions, class instances,
 * and built-in collection or asynchronous objects are rejected rather than
 * silently losing their type. Only enumerable own data properties are accepted;
 * non-enumerable properties and accessors, including symbol properties, are
 * rejected without invoking getters.
 *
 * Providers merge their defined properties over the nearest parent scope.
 * Component instance inputs can then apply their own final overrides without
 * mutating the shared provider value.
 *
 * Immutability is deliberately shallow and top-level: each resolved record is
 * cloned and frozen, while nested values retain their original identities and
 * must be treated as immutable by their owners.
 *
 * @experimental This foundation remains experimental until it has been proven
 * across multiple component families and their SSR and override contracts.
 */
declare function createKrnOptions<T extends object>(
  description: string,
  defaults: T,
): readonly [
  InjectionToken<Readonly<T>>,
  (patch: Partial<T> | (() => Partial<T>)) => FactoryProvider,
];

/**
 * Replaceable boundary for writing plain text to the system clipboard.
 *
 * The default writer prefers the asynchronous Clipboard API and only uses the
 * Angular CDK fallback when that modern API is absent. Consumers can replace
 * this token in tests or constrained rendering environments.
 */
interface KrnClipboardWriter {
  writeText(value: string): Promise<void>;
}
/** Application-replaceable clipboard writer used by KERN copy affordances. */
declare const KRN_CLIPBOARD_WRITER: InjectionToken<KrnClipboardWriter>;

type KrnScheduledHandle = ReturnType<typeof globalThis.setTimeout>;
/**
 * The browser capabilities Kern uses at runtime.
 *
 * Components should inject this contract instead of reading global `window`,
 * `document`, storage, or media-query APIs directly. Tests and non-browser
 * renderers can replace it through `provideKern`.
 */
interface KrnPlatformAdapter {
  readonly document: Document;
  readonly isBrowser: boolean;
  readonly window: (Window & typeof globalThis) | null;
  readonly localStorage: Storage | null;
  matchMedia(query: string): MediaQueryList | null;
  requestAnimationFrame(callback: FrameRequestCallback): number | null;
  cancelAnimationFrame(handle: number | null): void;
  schedule(callback: () => void, delay?: number): KrnScheduledHandle | null;
  cancelScheduled(handle: KrnScheduledHandle | null): void;
  queueMicrotask(callback: () => void): void;
  now(): number;
}
declare function krnIsNode(platform: KrnPlatformAdapter, value: unknown): value is Node;
declare function krnIsElement(platform: KrnPlatformAdapter, value: unknown): value is Element;
declare function krnIsHtmlElement(
  platform: KrnPlatformAdapter,
  value: unknown,
): value is HTMLElement;
declare function krnIsInputElement(
  platform: KrnPlatformAdapter,
  value: unknown,
): value is HTMLInputElement;
/**
 * Resolves Kern's effective motion preference.
 *
 * The explicit application preference wins over the operating-system media
 * query. Server renderers return `true` so animation-dependent teardown never
 * delays deterministic rendering.
 */
declare function krnPrefersReducedMotion(platform: KrnPlatformAdapter): boolean;
/** Replaceable platform boundary used by all new low-level Kern services. */
declare const KRN_PLATFORM: InjectionToken<KrnPlatformAdapter>;
/** Resolves the element where application-level overlay portals are attached. */
type KrnOverlayHostResolver = () => HTMLElement | null;
declare const KRN_OVERLAY_HOST: InjectionToken<KrnOverlayHostResolver>;

type KrnOverlayInitialFocus = 'first-tabbable' | 'surface' | string;
/**
 * Coordinates modal surfaces rendered in the application tree.
 *
 * The coordinator deliberately owns global side effects so that nested dialogs
 * share one scroll lock, only the top surface receives Escape, and background
 * content is restored to its exact previous state.
 */
declare class KrnOverlayCoordinator {
  private readonly platform;
  private readonly interactivity;
  private readonly destroyRef;
  private readonly stack;
  private readonly background;
  private readonly overlayOrigins;
  private previousOverflow;
  private recentPointerOrigin;
  constructor();
  activate(id: string, host?: HTMLElement | null, restoreFocus?: HTMLElement | null): void;
  deactivate(id: string, focusRestoreDelay?: number): void;
  isTop(id: string): boolean;
  /**
   * Associates a CDK overlay branch with the element that opened it.
   *
   * Kern components call this after attachment. Custom overlay primitives that use the
   * `krn-overlay-pane` marker must register too, otherwise a modal treats their branch as
   * unrelated background content.
   */
  registerOverlayOwnership(
    origin: HTMLElement,
    pane: HTMLElement,
    backdrop?: HTMLElement | null,
  ): void;
  /**
   * Returns whether an event/focus target belongs to an overlay opened from
   * `owner`, including recursively nested overlay branches.
   *
   * This is the active-zone boundary used by non-modal connected overlays:
   * moving focus or a pointer into a child dropdown must not close its parent.
   */
  isOwnedBy(owner: HTMLElement, target: EventTarget | null): boolean;
  focusInitial(panel: HTMLElement, initialFocus: KrnOverlayInitialFocus): void;
  private firstTabbable;
  private resolveRestoreFocus;
  private queryWithin;
  private syncBackground;
  private belongsToTopOverlay;
  private originBelongsToHost;
  private overlayContainerBranch;
  private hide;
  private restoreBackground;
  private isInert;
  static ɵfac: i0.ɵɵFactoryDeclaration<KrnOverlayCoordinator, never>;
  static ɵprov: i0.ɵɵInjectableDeclaration<KrnOverlayCoordinator>;
}

export {
  KRN_CLIPBOARD_WRITER,
  KRN_OVERLAY_HOST,
  KRN_PLATFORM,
  KrnIdService,
  KrnOverlayCoordinator,
  createKrnOptions,
  isKrnComponentContent,
  isKrnTemplateContent,
  krnIsElement,
  krnIsHtmlElement,
  krnIsInputElement,
  krnIsNode,
  krnPrefersReducedMotion,
};
export type {
  KrnClipboardWriter,
  KrnContent,
  KrnItemContentContext,
  KrnOverlayHostResolver,
  KrnOverlayInitialFocus,
  KrnPlatformAdapter,
  KrnScheduledHandle,
};
