/**
 * Committed public API baseline for @kern-ui/angular/core.
 *
 * Generated by tools/verify-kern-api-baseline.mjs. Update intentionally with
 * `npm run api:baseline:write` and review the declaration diff.
 */

import * as _angular_core from '@angular/core';
import { InjectionToken, Provider, Signal, EnvironmentProviders } from '@angular/core';
import { KrnOverlayHostResolver, KrnPlatformAdapter } from '@kern-ui/angular/cdk';
import { KrnI18nValue } from '@kern-ui/angular/i18n';

declare const KRN_BRAND_STEPS: readonly [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950];
type KrnBrandStep = (typeof KRN_BRAND_STEPS)[number];
type KrnBrandPalette = Readonly<Record<KrnBrandStep, string>>;
interface KrnOklchColor {
  readonly l: number;
  readonly c: number;
  readonly h: number;
}
/** Parses #RGB, #RGBA, #RRGGBB and #RRGGBBAA without touching browser APIs. */
declare function parseHexColor(value: string): KrnOklchColor | null;
/**
 * Builds a perceptually even OKLCH palette from a hex brand color.
 * It is deterministic and browser-independent, so it is safe during SSR.
 */
declare function generateKrnBrandPalette(brandColor: string): KrnBrandPalette | null;
declare function krnBrandPaletteVariables(
  palette: KrnBrandPalette,
): Readonly<Record<`--krn-color-brand-${KrnBrandStep}`, string>>;

interface KrnIconDefinition {
  readonly name: string;
  readonly paths: readonly string[];
  readonly viewBox?: string;
  readonly fill?: 'none' | 'currentColor';
}
declare const KRN_BUILT_IN_ICONS: readonly [
  {
    readonly name: 'menu';
    readonly paths: readonly ['M4 7h16M4 12h16M4 17h16'];
  },
  {
    readonly name: 'close';
    readonly paths: readonly ['m6 6 12 12M18 6 6 18'];
  },
  {
    readonly name: 'chevron-left';
    readonly paths: readonly ['m15 18-6-6 6-6'];
  },
  {
    readonly name: 'chevron-right';
    readonly paths: readonly ['m9 18 6-6-6-6'];
  },
  {
    readonly name: 'chevron-down';
    readonly paths: readonly ['m6 9 6 6 6-6'];
  },
  {
    readonly name: 'check';
    readonly paths: readonly ['m5 12 4 4L19 6'];
  },
  {
    readonly name: 'plus';
    readonly paths: readonly ['M12 5v14M5 12h14'];
  },
  {
    readonly name: 'minus';
    readonly paths: readonly ['M5 12h14'];
  },
  {
    readonly name: 'search';
    readonly paths: readonly ['M21 21l-4.35-4.35', 'M11 18a7 7 0 1 1 0-14 7 7 0 0 1 0 14Z'];
  },
  {
    readonly name: 'settings';
    readonly paths: readonly [
      'M12 15.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Z',
      'M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.83 2.83-.06-.06a1.7 1.7 0 0 0-1.88-.34 1.7 1.7 0 0 0-1.03 1.56V21h-4v-.08A1.7 1.7 0 0 0 8.97 19.4a1.7 1.7 0 0 0-1.88.34l-.06.06-2.83-2.83.06-.06A1.7 1.7 0 0 0 4.6 15a1.7 1.7 0 0 0-1.52-1.03H3v-4h.08A1.7 1.7 0 0 0 4.6 8.97a1.7 1.7 0 0 0-.34-1.88l-.06-.06L7.03 4.2l.06.06A1.7 1.7 0 0 0 8.97 4.6 1.7 1.7 0 0 0 10 3.08V3h4v.08a1.7 1.7 0 0 0 1.03 1.52 1.7 1.7 0 0 0 1.88-.34l.06-.06 2.83 2.83-.06.06a1.7 1.7 0 0 0-.34 1.88A1.7 1.7 0 0 0 20.92 10H21v4h-.08A1.7 1.7 0 0 0 19.4 15Z',
    ];
  },
];
type KrnBuiltInIconName = (typeof KRN_BUILT_IN_ICONS)[number]['name'];
type KrnIconName = KrnBuiltInIconName | (string & Record<never, never>);
type KrnIconSize = 'sm' | 'md' | 'lg' | number;
declare const KRN_ICONS: InjectionToken<readonly (readonly KrnIconDefinition[])[]>;
declare function provideKrnIcons(...icons: readonly KrnIconDefinition[]): readonly Provider[];
declare class KrnIconRegistry {
  #private;
  constructor();
  register(...icons: readonly KrnIconDefinition[]): void;
  resolve(name: string): KrnIconDefinition | undefined;
  static ɵfac: _angular_core.ɵɵFactoryDeclaration<KrnIconRegistry, never>;
  static ɵprov: _angular_core.ɵɵInjectableDeclaration<KrnIconRegistry>;
}
declare class KrnIcon {
  private readonly registry;
  readonly name: _angular_core.InputSignal<KrnIconName>;
  readonly size: _angular_core.InputSignal<KrnIconSize>;
  readonly label: _angular_core.InputSignal<string | null>;
  protected readonly definition: _angular_core.Signal<KrnIconDefinition | undefined>;
  protected readonly resolvedSize: _angular_core.Signal<string>;
  static ɵfac: _angular_core.ɵɵFactoryDeclaration<KrnIcon, never>;
  static ɵcmp: _angular_core.ɵɵComponentDeclaration<
    KrnIcon,
    'krn-icon',
    never,
    {
      name: { alias: 'name'; required: true; isSignal: true };
      size: { alias: 'size'; required: false; isSignal: true };
      label: { alias: 'label'; required: false; isSignal: true };
    },
    {},
    never,
    never,
    true,
    never
  >;
}

/**
 * Kern's public token contract.
 *
 * The values are CSS custom-property references on purpose: application code can
 * share the exact same semantic vocabulary as component styles without copying
 * theme values into JavaScript bundles.
 */
declare const KRN_TOKEN_NAMES: {
  readonly color: {
    readonly canvas: '--krn-color-canvas';
    readonly surface: '--krn-color-surface';
    readonly surfaceSubtle: '--krn-color-surface-subtle';
    readonly surfaceRaised: '--krn-color-surface-raised';
    readonly surfaceSunken: '--krn-color-surface-sunken';
    readonly surfaceInverse: '--krn-color-surface-inverse';
    readonly surfaceHover: '--krn-color-surface-hover';
    readonly surfaceDisabled: '--krn-color-surface-disabled';
    readonly surfaceOverlay: '--krn-color-surface-overlay';
    readonly text: '--krn-color-text';
    readonly textMuted: '--krn-color-text-muted';
    readonly textSubtle: '--krn-color-text-subtle';
    readonly textDisabled: '--krn-color-text-disabled';
    readonly textPlaceholder: '--krn-color-text-placeholder';
    readonly textInverse: '--krn-color-text-inverse';
    readonly border: '--krn-color-border';
    readonly borderStrong: '--krn-color-border-strong';
    readonly borderInteractive: '--krn-color-border-interactive';
    readonly primary: '--krn-color-primary';
    readonly primaryHover: '--krn-color-primary-hover';
    readonly primaryActive: '--krn-color-primary-active';
    readonly primarySubtle: '--krn-color-primary-subtle';
    readonly onPrimary: '--krn-color-on-primary';
    readonly link: '--krn-color-link';
    readonly focus: '--krn-color-focus';
    readonly selection: '--krn-color-selection';
    readonly backdrop: '--krn-color-backdrop';
    readonly success: '--krn-color-success';
    readonly successSubtle: '--krn-color-success-subtle';
    readonly onSuccess: '--krn-color-on-success';
    readonly warning: '--krn-color-warning';
    readonly warningSubtle: '--krn-color-warning-subtle';
    readonly onWarning: '--krn-color-on-warning';
    readonly danger: '--krn-color-danger';
    readonly dangerSubtle: '--krn-color-danger-subtle';
    readonly onDanger: '--krn-color-on-danger';
    readonly info: '--krn-color-info';
    readonly infoSubtle: '--krn-color-info-subtle';
    readonly onInfo: '--krn-color-on-info';
  };
  readonly calendar: {
    readonly dayHover: '--krn-calendar-day-hover';
    readonly rangeSurface: '--krn-calendar-range-surface';
    readonly rangeText: '--krn-calendar-range-text';
    readonly selectedSurface: '--krn-calendar-selected-surface';
    readonly selectedText: '--krn-calendar-selected-text';
  };
  readonly space: {
    readonly 0: '--krn-space-0';
    readonly px: '--krn-space-px';
    readonly 0.5: '--krn-space-0-5';
    readonly 1: '--krn-space-1';
    readonly 1.5: '--krn-space-1-5';
    readonly 2: '--krn-space-2';
    readonly 3: '--krn-space-3';
    readonly 4: '--krn-space-4';
    readonly 5: '--krn-space-5';
    readonly 6: '--krn-space-6';
    readonly 8: '--krn-space-8';
    readonly 10: '--krn-space-10';
    readonly 12: '--krn-space-12';
    readonly 16: '--krn-space-16';
    readonly 20: '--krn-space-20';
    readonly 24: '--krn-space-24';
  };
  readonly radius: {
    readonly none: '--krn-radius-none';
    readonly xs: '--krn-radius-xs';
    readonly sm: '--krn-radius-sm';
    readonly md: '--krn-radius-md';
    readonly lg: '--krn-radius-lg';
    readonly xl: '--krn-radius-xl';
    readonly full: '--krn-radius-full';
  };
  readonly border: {
    readonly none: '--krn-border-width-0';
    readonly standard: '--krn-border-width-1';
    readonly strong: '--krn-border-width-2';
  };
  readonly opacity: {
    readonly disabled: '--krn-opacity-disabled';
    readonly muted: '--krn-opacity-muted';
    readonly overlay: '--krn-opacity-overlay';
  };
  readonly shadow: {
    readonly xs: '--krn-shadow-xs';
    readonly sm: '--krn-shadow-sm';
    readonly md: '--krn-shadow-md';
    readonly lg: '--krn-shadow-lg';
    readonly overlay: '--krn-shadow-overlay';
  };
  readonly typography: {
    readonly fontSans: '--krn-font-family-sans';
    readonly fontMono: '--krn-font-family-mono';
    readonly sizeXs: '--krn-font-size-xs';
    readonly sizeSm: '--krn-font-size-sm';
    readonly sizeMd: '--krn-font-size-md';
    readonly sizeLg: '--krn-font-size-lg';
    readonly sizeXl: '--krn-font-size-xl';
    readonly size2xl: '--krn-font-size-2xl';
    readonly size3xl: '--krn-font-size-3xl';
    readonly size4xl: '--krn-font-size-4xl';
    readonly lineNone: '--krn-line-height-none';
    readonly lineTight: '--krn-line-height-tight';
    readonly lineHeading: '--krn-line-height-heading';
    readonly lineBody: '--krn-line-height-body';
    readonly lineRelaxed: '--krn-line-height-relaxed';
    readonly weightRegular: '--krn-font-weight-regular';
    readonly weightMedium: '--krn-font-weight-medium';
    readonly weightSemibold: '--krn-font-weight-semibold';
    readonly weightBold: '--krn-font-weight-bold';
    readonly trackingTight: '--krn-letter-spacing-tight';
    readonly trackingNormal: '--krn-letter-spacing-normal';
    readonly trackingWide: '--krn-letter-spacing-wide';
  };
  readonly motion: {
    readonly instant: '--krn-motion-duration-instant';
    readonly fast: '--krn-motion-duration-fast';
    readonly normal: '--krn-motion-duration-normal';
    readonly slow: '--krn-motion-duration-slow';
    readonly deliberate: '--krn-motion-duration-deliberate';
    readonly standard: '--krn-motion-ease-standard';
    readonly enter: '--krn-motion-ease-enter';
    readonly exit: '--krn-motion-ease-exit';
    readonly spring: '--krn-motion-ease-spring';
  };
  readonly control: {
    readonly heightSm: '--krn-control-height-sm';
    readonly heightMd: '--krn-control-height-md';
    readonly heightLg: '--krn-control-height-lg';
    readonly paddingInline: '--krn-control-padding-inline';
    readonly touchTargetMin: '--krn-touch-target-min';
    readonly iconSm: '--krn-icon-size-sm';
    readonly iconMd: '--krn-icon-size-md';
    readonly iconLg: '--krn-icon-size-lg';
    readonly iconStroke: '--krn-icon-stroke-width';
    readonly dataRow: '--krn-data-row-size';
  };
  readonly focus: {
    readonly width: '--krn-focus-ring-width';
    readonly formWidth: '--krn-form-focus-ring-width';
    readonly offset: '--krn-focus-ring-offset';
    readonly ring: '--krn-focus-ring';
    readonly dangerRing: '--krn-focus-ring-danger';
  };
  readonly layer: {
    readonly base: '--krn-z-base';
    readonly sticky: '--krn-z-sticky';
    readonly dropdown: '--krn-z-dropdown';
    readonly overlay: '--krn-z-overlay';
    readonly modal: '--krn-z-modal';
    readonly toast: '--krn-z-toast';
    readonly popover: '--krn-z-popover';
    readonly drawer: '--krn-z-drawer';
  };
  readonly breakpoint: {
    readonly sm: '--krn-breakpoint-sm';
    readonly md: '--krn-breakpoint-md';
    readonly lg: '--krn-breakpoint-lg';
    readonly xl: '--krn-breakpoint-xl';
  };
  readonly container: {
    readonly sm: '--krn-container-sm';
    readonly md: '--krn-container-md';
    readonly lg: '--krn-container-lg';
    readonly xl: '--krn-container-xl';
  };
  readonly appearance: {
    readonly borderSubtle: '--krn-color-border-subtle';
    readonly brandSolid: '--krn-color-brand-solid';
    readonly brandSurface: '--krn-color-brand-surface';
    readonly brandText: '--krn-color-brand-text';
    readonly brandBorder: '--krn-color-brand-border';
    readonly onBrand: '--krn-color-on-brand';
    readonly accent: '--krn-color-accent';
    readonly accentSoft: '--krn-color-accent-soft';
    readonly accentStrong: '--krn-color-accent-strong';
    readonly accentBorder: '--krn-color-accent-border';
    readonly onAccent: '--krn-color-on-accent';
    readonly successSolid: '--krn-color-success-solid';
    readonly successSoft: '--krn-color-success-soft';
    readonly successSurface: '--krn-color-success-surface';
    readonly successText: '--krn-color-success-text';
    readonly successStrong: '--krn-color-success-strong';
    readonly successBorder: '--krn-color-success-border';
    readonly warningSolid: '--krn-color-warning-solid';
    readonly warningSoft: '--krn-color-warning-soft';
    readonly warningSurface: '--krn-color-warning-surface';
    readonly warningText: '--krn-color-warning-text';
    readonly warningStrong: '--krn-color-warning-strong';
    readonly warningBorder: '--krn-color-warning-border';
    readonly dangerSolid: '--krn-color-danger-solid';
    readonly dangerSoft: '--krn-color-danger-soft';
    readonly dangerSurface: '--krn-color-danger-surface';
    readonly dangerText: '--krn-color-danger-text';
    readonly dangerStrong: '--krn-color-danger-strong';
    readonly dangerBorder: '--krn-color-danger-border';
    readonly infoSolid: '--krn-color-info-solid';
    readonly infoSoft: '--krn-color-info-soft';
    readonly infoSurface: '--krn-color-info-surface';
    readonly infoText: '--krn-color-info-text';
    readonly infoStrong: '--krn-color-info-strong';
    readonly infoBorder: '--krn-color-info-border';
  };
  readonly typographyRecipe: {
    readonly familyUi: '--krn-font-family-ui';
    readonly sizeControl: '--krn-font-size-control';
    readonly body: '--krn-font-body';
    readonly bodySm: '--krn-font-body-sm';
    readonly label: '--krn-font-label';
    readonly labelSm: '--krn-font-label-sm';
    readonly headingSm: '--krn-font-heading-sm';
    readonly headingLg: '--krn-font-heading-lg';
    readonly headingXl: '--krn-font-heading-xl';
  };
  readonly motionRecipe: {
    readonly fast: '--krn-motion-fast';
    readonly moderate: '--krn-motion-moderate';
    readonly slow: '--krn-motion-slow';
    readonly interaction: '--krn-motion-duration-interaction';
    readonly selection: '--krn-motion-duration-selection';
    readonly enterDuration: '--krn-motion-duration-enter';
    readonly exitDuration: '--krn-motion-duration-exit';
    readonly layout: '--krn-motion-duration-layout';
    readonly feedback: '--krn-motion-duration-feedback';
    readonly spinner: '--krn-motion-duration-spinner';
    readonly progress: '--krn-motion-duration-progress';
    readonly skeleton: '--krn-motion-duration-skeleton';
    readonly continuousIterations: '--krn-motion-iteration-continuous';
    readonly standard: '--krn-ease-standard';
    readonly enter: '--krn-ease-enter';
  };
  readonly radiusRecipe: {
    readonly control: '--krn-radius-control';
    readonly surface: '--krn-radius-surface';
    readonly overlay: '--krn-radius-overlay';
    readonly pill: '--krn-radius-pill';
  };
  readonly controlRecipe: {
    readonly sizeSm: '--krn-control-size-sm';
    readonly size: '--krn-control-size';
  };
  readonly density: {
    readonly scale: '--krn-density-scale';
    readonly gap: '--krn-density-gap';
    readonly sectionGap: '--krn-density-section-gap';
    readonly cellPaddingBlock: '--krn-density-cell-padding-block';
    readonly cellPaddingInline: '--krn-density-cell-padding-inline';
    readonly tableRowHeight: '--krn-table-row-height';
  };
  readonly shadowRecipe: {
    readonly control: '--krn-shadow-control';
    readonly floating: '--krn-shadow-floating';
    readonly drawer: '--krn-shadow-drawer';
  };
  readonly chart: {
    readonly 1: '--krn-chart-1';
    readonly 2: '--krn-chart-2';
    readonly 3: '--krn-chart-3';
    readonly 4: '--krn-chart-4';
    readonly 5: '--krn-chart-5';
  };
};
type KrnTokenTree = {
  readonly [key: string]: string | KrnTokenTree;
};
type KrnTokenTier = 'primitive' | 'semantic' | 'component' | 'recipe';
type KrnTokenVisibility = 'public' | 'internal';
type KrnTokenName = {
  readonly [
    Group in keyof typeof KRN_TOKEN_NAMES
  ]: (typeof KRN_TOKEN_NAMES)[Group][keyof (typeof KRN_TOKEN_NAMES)[Group]];
}[keyof typeof KRN_TOKEN_NAMES];
interface KrnTokenDescriptor {
  readonly name: string;
  readonly path: string;
  readonly tier: KrnTokenTier;
  readonly visibility: KrnTokenVisibility;
}
/**
 * Machine-readable registry used by documentation and contract verification.
 * Internal entries are included for parity checks but are not part of
 * `krnTokens` and may change without a deprecation cycle before 1.0.
 */
declare const KRN_TOKEN_MANIFEST: readonly KrnTokenDescriptor[];
type KrnCssReferenceTree<T extends KrnTokenTree> = {
  readonly [K in keyof T]: T[K] extends string
    ? `var(${T[K]})`
    : T[K] extends KrnTokenTree
      ? KrnCssReferenceTree<T[K]>
      : never;
};
/** Ready-to-use `var(--krn-*)` values, strongly typed to the token contract. */
declare const krnTokens: KrnCssReferenceTree<{
  readonly color: {
    readonly canvas: '--krn-color-canvas';
    readonly surface: '--krn-color-surface';
    readonly surfaceSubtle: '--krn-color-surface-subtle';
    readonly surfaceRaised: '--krn-color-surface-raised';
    readonly surfaceSunken: '--krn-color-surface-sunken';
    readonly surfaceInverse: '--krn-color-surface-inverse';
    readonly surfaceHover: '--krn-color-surface-hover';
    readonly surfaceDisabled: '--krn-color-surface-disabled';
    readonly surfaceOverlay: '--krn-color-surface-overlay';
    readonly text: '--krn-color-text';
    readonly textMuted: '--krn-color-text-muted';
    readonly textSubtle: '--krn-color-text-subtle';
    readonly textDisabled: '--krn-color-text-disabled';
    readonly textPlaceholder: '--krn-color-text-placeholder';
    readonly textInverse: '--krn-color-text-inverse';
    readonly border: '--krn-color-border';
    readonly borderStrong: '--krn-color-border-strong';
    readonly borderInteractive: '--krn-color-border-interactive';
    readonly primary: '--krn-color-primary';
    readonly primaryHover: '--krn-color-primary-hover';
    readonly primaryActive: '--krn-color-primary-active';
    readonly primarySubtle: '--krn-color-primary-subtle';
    readonly onPrimary: '--krn-color-on-primary';
    readonly link: '--krn-color-link';
    readonly focus: '--krn-color-focus';
    readonly selection: '--krn-color-selection';
    readonly backdrop: '--krn-color-backdrop';
    readonly success: '--krn-color-success';
    readonly successSubtle: '--krn-color-success-subtle';
    readonly onSuccess: '--krn-color-on-success';
    readonly warning: '--krn-color-warning';
    readonly warningSubtle: '--krn-color-warning-subtle';
    readonly onWarning: '--krn-color-on-warning';
    readonly danger: '--krn-color-danger';
    readonly dangerSubtle: '--krn-color-danger-subtle';
    readonly onDanger: '--krn-color-on-danger';
    readonly info: '--krn-color-info';
    readonly infoSubtle: '--krn-color-info-subtle';
    readonly onInfo: '--krn-color-on-info';
  };
  readonly calendar: {
    readonly dayHover: '--krn-calendar-day-hover';
    readonly rangeSurface: '--krn-calendar-range-surface';
    readonly rangeText: '--krn-calendar-range-text';
    readonly selectedSurface: '--krn-calendar-selected-surface';
    readonly selectedText: '--krn-calendar-selected-text';
  };
  readonly space: {
    readonly 0: '--krn-space-0';
    readonly px: '--krn-space-px';
    readonly 0.5: '--krn-space-0-5';
    readonly 1: '--krn-space-1';
    readonly 1.5: '--krn-space-1-5';
    readonly 2: '--krn-space-2';
    readonly 3: '--krn-space-3';
    readonly 4: '--krn-space-4';
    readonly 5: '--krn-space-5';
    readonly 6: '--krn-space-6';
    readonly 8: '--krn-space-8';
    readonly 10: '--krn-space-10';
    readonly 12: '--krn-space-12';
    readonly 16: '--krn-space-16';
    readonly 20: '--krn-space-20';
    readonly 24: '--krn-space-24';
  };
  readonly radius: {
    readonly none: '--krn-radius-none';
    readonly xs: '--krn-radius-xs';
    readonly sm: '--krn-radius-sm';
    readonly md: '--krn-radius-md';
    readonly lg: '--krn-radius-lg';
    readonly xl: '--krn-radius-xl';
    readonly full: '--krn-radius-full';
  };
  readonly border: {
    readonly none: '--krn-border-width-0';
    readonly standard: '--krn-border-width-1';
    readonly strong: '--krn-border-width-2';
  };
  readonly opacity: {
    readonly disabled: '--krn-opacity-disabled';
    readonly muted: '--krn-opacity-muted';
    readonly overlay: '--krn-opacity-overlay';
  };
  readonly shadow: {
    readonly xs: '--krn-shadow-xs';
    readonly sm: '--krn-shadow-sm';
    readonly md: '--krn-shadow-md';
    readonly lg: '--krn-shadow-lg';
    readonly overlay: '--krn-shadow-overlay';
  };
  readonly typography: {
    readonly fontSans: '--krn-font-family-sans';
    readonly fontMono: '--krn-font-family-mono';
    readonly sizeXs: '--krn-font-size-xs';
    readonly sizeSm: '--krn-font-size-sm';
    readonly sizeMd: '--krn-font-size-md';
    readonly sizeLg: '--krn-font-size-lg';
    readonly sizeXl: '--krn-font-size-xl';
    readonly size2xl: '--krn-font-size-2xl';
    readonly size3xl: '--krn-font-size-3xl';
    readonly size4xl: '--krn-font-size-4xl';
    readonly lineNone: '--krn-line-height-none';
    readonly lineTight: '--krn-line-height-tight';
    readonly lineHeading: '--krn-line-height-heading';
    readonly lineBody: '--krn-line-height-body';
    readonly lineRelaxed: '--krn-line-height-relaxed';
    readonly weightRegular: '--krn-font-weight-regular';
    readonly weightMedium: '--krn-font-weight-medium';
    readonly weightSemibold: '--krn-font-weight-semibold';
    readonly weightBold: '--krn-font-weight-bold';
    readonly trackingTight: '--krn-letter-spacing-tight';
    readonly trackingNormal: '--krn-letter-spacing-normal';
    readonly trackingWide: '--krn-letter-spacing-wide';
  };
  readonly motion: {
    readonly instant: '--krn-motion-duration-instant';
    readonly fast: '--krn-motion-duration-fast';
    readonly normal: '--krn-motion-duration-normal';
    readonly slow: '--krn-motion-duration-slow';
    readonly deliberate: '--krn-motion-duration-deliberate';
    readonly standard: '--krn-motion-ease-standard';
    readonly enter: '--krn-motion-ease-enter';
    readonly exit: '--krn-motion-ease-exit';
    readonly spring: '--krn-motion-ease-spring';
  };
  readonly control: {
    readonly heightSm: '--krn-control-height-sm';
    readonly heightMd: '--krn-control-height-md';
    readonly heightLg: '--krn-control-height-lg';
    readonly paddingInline: '--krn-control-padding-inline';
    readonly touchTargetMin: '--krn-touch-target-min';
    readonly iconSm: '--krn-icon-size-sm';
    readonly iconMd: '--krn-icon-size-md';
    readonly iconLg: '--krn-icon-size-lg';
    readonly iconStroke: '--krn-icon-stroke-width';
    readonly dataRow: '--krn-data-row-size';
  };
  readonly focus: {
    readonly width: '--krn-focus-ring-width';
    readonly formWidth: '--krn-form-focus-ring-width';
    readonly offset: '--krn-focus-ring-offset';
    readonly ring: '--krn-focus-ring';
    readonly dangerRing: '--krn-focus-ring-danger';
  };
  readonly layer: {
    readonly base: '--krn-z-base';
    readonly sticky: '--krn-z-sticky';
    readonly dropdown: '--krn-z-dropdown';
    readonly overlay: '--krn-z-overlay';
    readonly modal: '--krn-z-modal';
    readonly toast: '--krn-z-toast';
    readonly popover: '--krn-z-popover';
    readonly drawer: '--krn-z-drawer';
  };
  readonly breakpoint: {
    readonly sm: '--krn-breakpoint-sm';
    readonly md: '--krn-breakpoint-md';
    readonly lg: '--krn-breakpoint-lg';
    readonly xl: '--krn-breakpoint-xl';
  };
  readonly container: {
    readonly sm: '--krn-container-sm';
    readonly md: '--krn-container-md';
    readonly lg: '--krn-container-lg';
    readonly xl: '--krn-container-xl';
  };
  readonly appearance: {
    readonly borderSubtle: '--krn-color-border-subtle';
    readonly brandSolid: '--krn-color-brand-solid';
    readonly brandSurface: '--krn-color-brand-surface';
    readonly brandText: '--krn-color-brand-text';
    readonly brandBorder: '--krn-color-brand-border';
    readonly onBrand: '--krn-color-on-brand';
    readonly accent: '--krn-color-accent';
    readonly accentSoft: '--krn-color-accent-soft';
    readonly accentStrong: '--krn-color-accent-strong';
    readonly accentBorder: '--krn-color-accent-border';
    readonly onAccent: '--krn-color-on-accent';
    readonly successSolid: '--krn-color-success-solid';
    readonly successSoft: '--krn-color-success-soft';
    readonly successSurface: '--krn-color-success-surface';
    readonly successText: '--krn-color-success-text';
    readonly successStrong: '--krn-color-success-strong';
    readonly successBorder: '--krn-color-success-border';
    readonly warningSolid: '--krn-color-warning-solid';
    readonly warningSoft: '--krn-color-warning-soft';
    readonly warningSurface: '--krn-color-warning-surface';
    readonly warningText: '--krn-color-warning-text';
    readonly warningStrong: '--krn-color-warning-strong';
    readonly warningBorder: '--krn-color-warning-border';
    readonly dangerSolid: '--krn-color-danger-solid';
    readonly dangerSoft: '--krn-color-danger-soft';
    readonly dangerSurface: '--krn-color-danger-surface';
    readonly dangerText: '--krn-color-danger-text';
    readonly dangerStrong: '--krn-color-danger-strong';
    readonly dangerBorder: '--krn-color-danger-border';
    readonly infoSolid: '--krn-color-info-solid';
    readonly infoSoft: '--krn-color-info-soft';
    readonly infoSurface: '--krn-color-info-surface';
    readonly infoText: '--krn-color-info-text';
    readonly infoStrong: '--krn-color-info-strong';
    readonly infoBorder: '--krn-color-info-border';
  };
  readonly typographyRecipe: {
    readonly familyUi: '--krn-font-family-ui';
    readonly sizeControl: '--krn-font-size-control';
    readonly body: '--krn-font-body';
    readonly bodySm: '--krn-font-body-sm';
    readonly label: '--krn-font-label';
    readonly labelSm: '--krn-font-label-sm';
    readonly headingSm: '--krn-font-heading-sm';
    readonly headingLg: '--krn-font-heading-lg';
    readonly headingXl: '--krn-font-heading-xl';
  };
  readonly motionRecipe: {
    readonly fast: '--krn-motion-fast';
    readonly moderate: '--krn-motion-moderate';
    readonly slow: '--krn-motion-slow';
    readonly interaction: '--krn-motion-duration-interaction';
    readonly selection: '--krn-motion-duration-selection';
    readonly enterDuration: '--krn-motion-duration-enter';
    readonly exitDuration: '--krn-motion-duration-exit';
    readonly layout: '--krn-motion-duration-layout';
    readonly feedback: '--krn-motion-duration-feedback';
    readonly spinner: '--krn-motion-duration-spinner';
    readonly progress: '--krn-motion-duration-progress';
    readonly skeleton: '--krn-motion-duration-skeleton';
    readonly continuousIterations: '--krn-motion-iteration-continuous';
    readonly standard: '--krn-ease-standard';
    readonly enter: '--krn-ease-enter';
  };
  readonly radiusRecipe: {
    readonly control: '--krn-radius-control';
    readonly surface: '--krn-radius-surface';
    readonly overlay: '--krn-radius-overlay';
    readonly pill: '--krn-radius-pill';
  };
  readonly controlRecipe: {
    readonly sizeSm: '--krn-control-size-sm';
    readonly size: '--krn-control-size';
  };
  readonly density: {
    readonly scale: '--krn-density-scale';
    readonly gap: '--krn-density-gap';
    readonly sectionGap: '--krn-density-section-gap';
    readonly cellPaddingBlock: '--krn-density-cell-padding-block';
    readonly cellPaddingInline: '--krn-density-cell-padding-inline';
    readonly tableRowHeight: '--krn-table-row-height';
  };
  readonly shadowRecipe: {
    readonly control: '--krn-shadow-control';
    readonly floating: '--krn-shadow-floating';
    readonly drawer: '--krn-shadow-drawer';
  };
  readonly chart: {
    readonly 1: '--krn-chart-1';
    readonly 2: '--krn-chart-2';
    readonly 3: '--krn-chart-3';
    readonly 4: '--krn-chart-4';
    readonly 5: '--krn-chart-5';
  };
}>;
type KrnSpace =
  | '0'
  | 'px'
  | '0.5'
  | '1'
  | '1.5'
  | '2'
  | '3'
  | '4'
  | '5'
  | '6'
  | '8'
  | '10'
  | '12'
  | '16'
  | '20'
  | '24';
type KrnRadius = keyof typeof KRN_TOKEN_NAMES.radius;
type KrnElevation = keyof typeof KRN_TOKEN_NAMES.shadow | 'none';
type KrnFoundationSize = 'sm' | 'md' | 'lg';
type KrnBreakpoint = 'sm' | 'md' | 'lg' | 'xl';
type KrnDensity = 'compact' | 'comfortable' | 'spacious';
type KrnTheme = 'light' | 'dark' | 'system' | 'high-contrast';
type KrnResolvedTheme = Exclude<KrnTheme, 'system'>;

interface KrnActionTranslations {
  readonly copyToClipboard: string;
  /**
   * Pending copy feedback. Optional so complete third-party dictionaries made
   * for earlier Kern versions remain source-compatible.
   */
  readonly copying?: string;
  readonly copied: string;
  readonly copyFailed: string;
  readonly moreActions: string;
}
interface KrnDataGridTranslations {
  readonly ariaLabel: string;
  readonly empty: string;
  readonly filterPlaceholder: string;
  readonly columns: string;
  readonly errorTitle: string;
  readonly loading: string;
  readonly clearFilter: string;
  readonly selectAllVisible: string;
  readonly selectAllPage: string;
  readonly scrollRegion: string;
  readonly expand: string;
  readonly expandRow: string;
  readonly collapseRow: string;
  readonly pagination: string;
  readonly previousPage: string;
  readonly nextPage: string;
  readonly rowCount: (count: number) => string;
  readonly filterLabel: (label: string) => string;
  readonly selectRow: (index: number) => string;
  readonly resizeColumn: (label: string) => string;
  readonly widthInPixels: (width: number) => string;
  readonly pageRange: (start: number, end: number, total: number) => string;
}
interface KrnDataDisplayTranslations {
  readonly copy: string;
  readonly copied: string;
  readonly codeCopied: string;
  readonly plainText: string;
  readonly tag: string;
  readonly people: string;
  readonly list: string;
  readonly accordion: string;
  readonly timeline: string;
  readonly rating: string;
  readonly copyCode: (language: string) => string;
  readonly removeItem: (label: string) => string;
  readonly keyboardShortcut: (keys: readonly string[]) => string;
  readonly ratingValue: (value: number, maximum: number) => string;
}
interface KrnCalendarTranslations {
  readonly previousMonth: string;
  readonly nextMonth: string;
  readonly today: string;
}
interface KrnChartTranslations {
  readonly empty?: string;
  readonly viewData: string;
  readonly hideData: string;
  readonly total: string;
  readonly sourceData: string;
  readonly labelColumn: string;
  readonly valueColumn: string;
  readonly shareColumn: string;
  readonly legend: string;
  /**
   * Backward-compatible template. Prefer `formatPercentOfTotal` for new
   * locale packs that need grammar beyond the `{value}` token.
   */
  readonly percentOfTotal: string;
  readonly formatPercentOfTotal?: (value: string) => string;
  readonly additionalItems?: (count: number) => string;
  readonly datumLabel: (label: string, value: string) => string;
  readonly datumShareLabel: (label: string, value: string, share: string) => string;
  readonly sourceDataCaption: (title: string, sourceData: string) => string;
  readonly summary: (title: string, items: readonly string[]) => string;
}
interface KrnDatePickerTranslations {
  readonly chooseDate: string;
  readonly chooseDateRange: string;
  readonly selectDate: string;
  readonly selectDateRange: string;
  readonly startDate: string;
  readonly endDate: string;
  readonly previousMonth: string;
  readonly nextMonth: string;
  readonly clear: string;
  readonly today: string;
  readonly done: string;
  readonly notSelected: string;
  readonly chooseStartDate: string;
  readonly chooseEndDate: string;
}
interface KrnTimePickerTranslations {
  readonly chooseTime: string;
  readonly selectTime: string;
  readonly twentyFourHourTime: string;
  readonly twentyFourHour: string;
  readonly time: string;
  readonly hour: string;
  readonly minute: string;
  readonly notSet: string;
  readonly keyboardHelp: string;
  readonly commonTimes: string;
  readonly clear: string;
  readonly apply: string;
}
interface KrnColorPickerTranslations {
  readonly chooseColor: string;
  readonly preview: string;
  readonly suggestedColors: string;
  readonly hue: string;
  readonly saturation: string;
  readonly lightness: string;
  readonly colorValue: string;
  readonly validColor: string;
  readonly invalidColor: string;
  readonly done: string;
  readonly useColor: (color: string) => string;
}
interface KrnToastTranslations {
  readonly ariaLabel: string;
  readonly stackLabel: string;
  readonly clearAll: string;
  readonly dismiss: string;
  readonly countLabel: (count: number) => string;
  readonly showRecent: string;
  readonly reviewEarlier: (count: number) => string;
  readonly limit: (visible: number, total: number) => string;
}
interface KrnNavigationTranslations {
  readonly optional: string;
  readonly progress: string;
  readonly menuEmpty: string;
  readonly breadcrumb: string;
  readonly breadcrumbMore: string;
  readonly breadcrumbShowAll: string;
  readonly navigationTree: string;
  readonly tree: string;
  readonly pagination: string;
  readonly previous: string;
  readonly next: string;
  readonly noResults: string;
  /** Backward-compatible template containing the `{page}` token. */
  readonly pageLabel: string;
  readonly formatPageLabel?: (page: number) => string;
  /** Backward-compatible template containing `{start}`, `{end}`, and `{total}`. */
  readonly resultRangeLabel: string;
  readonly formatResultRangeLabel?: (start: number, end: number, total: number) => string;
  readonly actions: string;
  readonly openMenu: string;
  readonly applicationMenu: string;
  readonly contextActions: string;
  readonly sections: string;
  readonly commandPalette: string;
  readonly searchCommandsPlaceholder: string;
  readonly commands: string;
  readonly escapeShortcut: string;
  readonly commandSearch: string;
  /** Backward-compatible template containing the `{query}` token. */
  readonly noCommandResults: string;
  readonly formatNoCommandResults?: (query: string) => string;
  readonly commandNavigate: string;
  readonly commandSelect: string;
  readonly commandAvailableOne: string;
  /** Backward-compatible template containing the `{count}` token. */
  readonly commandAvailableMany: string;
  readonly formatCommandAvailableMany?: (count: number) => string;
  readonly primary: string;
  readonly tableOfContentsTitle: string;
  readonly tableOfContents: string;
  readonly back: string;
  readonly skipToMainContent: string;
  readonly expandNode: (label: string) => string;
  readonly collapseNode: (label: string) => string;
  readonly loadingChildren?: (label: string) => string;
  readonly childrenLoadFailed?: (label: string) => string;
  readonly tabItemCount: (count: string | number) => string;
}
interface KrnFormTranslations {
  readonly chooseFiles: string;
  readonly fileSelectionRequired: string;
  readonly dropFilesHere: string;
  readonly selectedFiles: string;
  readonly unlimited: string;
  readonly increaseValue: string;
  readonly decreaseValue: string;
  readonly verificationCode: string;
  readonly tags: string;
  readonly addTag: string;
  readonly addTagPlaceholder: string;
  readonly added: string;
  readonly removed: string;
  readonly alreadyAdded: string;
  readonly selectOption: string;
  readonly selectOptions: string;
  readonly noOptions: string;
  readonly startTyping: string;
  readonly noMatches: string;
  readonly loadingOptions?: string;
  readonly optionsLoadFailed?: string;
  readonly showOptions: string;
  readonly showPassword: string;
  readonly hidePassword: string;
  readonly show: string;
  readonly hide: string;
  readonly search: string;
  readonly clearSearch: string;
  readonly value: string;
  readonly range: string;
  readonly minimumValue: string;
  readonly maximumValue: string;
  readonly chooseOption: string;
  readonly removeFile: (name: string) => string;
  readonly maximumFileCount: (name: string, count: number) => string;
  readonly unsupportedFileType: (name: string) => string;
  readonly fileTooLarge: (name: string, maximum: string) => string;
  readonly tagAdded: (tag: string) => string;
  readonly tagRemoved: (tag: string) => string;
  readonly tagAlreadyPresent: (tag: string) => string;
  readonly removeTag: (tag: string) => string;
  readonly verificationCharacter: (position: number, total: number) => string;
  readonly labeledValue: (label: string, value: number) => string;
}
interface KrnFeedbackTranslations {
  readonly dialog: string;
  readonly close: string;
  readonly moreInformation: string;
  readonly preview: string;
  readonly dismissMessage: string;
  readonly progress: string;
  readonly loading: string;
  readonly loadingInProgress: string;
  readonly emptyStateTitle: string;
  readonly errorStateTitle: string;
  readonly successStateTitle: string;
  readonly delete: string;
  readonly confirmPrompt: string;
  readonly confirm: string;
  readonly cancel: string;
}
interface KrnPatternTranslations {
  readonly globalSearch: string;
  readonly searchPlaceholder: string;
  readonly clearSearch: string;
  readonly resultLabel: (label: string) => string;
  readonly noSearchResults: (query: string) => string;
  readonly userActions: string;
  readonly notifications: string;
  readonly notificationCenter: string;
  readonly unread: string;
  readonly markAllRead: string;
  readonly notificationsEmpty: string;
  readonly filters: string;
  readonly all: string;
  readonly clearAll: string;
  readonly settings: string;
  readonly closeSettings: string;
  readonly actions: string;
  readonly masterList: string;
  readonly detail: string;
  readonly mobileNavigation: string;
  readonly signIn: string;
  readonly email: string;
  readonly invalidEmail: string;
  readonly password: string;
  readonly rememberMe: string;
  readonly forgotPassword: string;
  readonly signingIn: string;
  readonly unsavedChanges: string;
  readonly displayName: string;
  readonly displayNameRequired: string;
  readonly role: string;
  readonly bio: string;
  readonly bioMaximumLength: (maximumLength: number) => string;
  readonly timezone: string;
  readonly timezoneUnavailable: string;
  readonly saving: string;
  readonly saveProfile: string;
  readonly complete: string;
  readonly formProgress: string;
  readonly optional: string;
  readonly back: string;
  readonly continue: string;
  readonly step: string;
  readonly unreadCount: (count: number) => string;
  readonly activeFilters: (count: number) => string;
  readonly selectedCount: (count: number) => string;
  readonly minimumPasswordLength: (minimumLength: number) => string;
  readonly stepCounter: (current: number, total: number) => string;
  readonly profileTimezones: readonly {
    readonly value: string;
    readonly label: string;
  }[];
}
interface KrnLayoutTranslations {
  readonly mobileNavigation: string;
  readonly openNavigation: string;
  readonly closeNavigation: string;
  readonly primaryNavigation: string;
  readonly secondaryNavigation: string;
  readonly scrollableContent: string;
  readonly resizeAdjacentPanels: string;
}
interface KrnTranslations {
  readonly actions: KrnActionTranslations;
  readonly dataDisplay: KrnDataDisplayTranslations;
  readonly dataGrid: KrnDataGridTranslations;
  readonly calendar: KrnCalendarTranslations;
  readonly chart: KrnChartTranslations;
  readonly datePicker: KrnDatePickerTranslations;
  readonly timePicker: KrnTimePickerTranslations;
  readonly colorPicker: KrnColorPickerTranslations;
  readonly toast: KrnToastTranslations;
  readonly navigation: KrnNavigationTranslations;
  readonly forms: KrnFormTranslations;
  readonly feedback: KrnFeedbackTranslations;
  readonly patterns: KrnPatternTranslations;
  readonly layout: KrnLayoutTranslations;
}
type KrnTranslationsPatch = {
  readonly [Group in keyof KrnTranslations]?: Partial<KrnTranslations[Group]>;
};
/**
 * Resolves a typed translation formatter or, for backward compatibility,
 * interpolates only exact `{token}` entries from a legacy string template.
 *
 * Interpolation is single-pass: replacement values are text, are never
 * evaluated, and cannot introduce a second placeholder expansion.
 */
declare function krnFormatTranslation<Arguments extends readonly unknown[]>(
  template: string,
  parameters: Readonly<Record<string, string | number>>,
  formatter: ((...args: Arguments) => string) | undefined,
  ...args: Arguments
): string;
declare const KRN_ENGLISH_TRANSLATIONS: Readonly<KrnTranslations>;
/**
 * Creates an immutable, complete translation set from a typed partial
 * override. When a patch overrides a legacy template without its corresponding
 * typed formatter, the resulting complete dictionary derives a safe formatter
 * from that template instead of retaining the unrelated English formatter.
 */
declare function createKrnTranslations(patch?: KrnTranslationsPatch): Readonly<KrnTranslations>;
/**
 * Reactive, injector-scoped locale and translation state.
 *
 * Existing `KRN_TRANSLATIONS` consumers receive the stable `dictionary` view;
 * its frozen property getters read the same signal, so templates and computed
 * values react without replacing the public translation schema.
 */
declare class KrnI18n {
  private readonly localeState;
  private readonly translationState;
  readonly locale: Signal<string>;
  readonly translations: Signal<Readonly<KrnTranslations>>;
  readonly dictionary: Readonly<KrnTranslations>;
  /** Updates locale formatting while retaining the active dictionary. */
  setLocale(locale: string): void;
  /** Replaces the complete dictionary derived from Kern's English schema. */
  setTranslations(translations: KrnTranslationsPatch): void;
  /** Updates locale and copy through one synchronous runtime operation. */
  activate(locale: string, translations: KrnTranslationsPatch): void;
  static ɵfac: _angular_core.ɵɵFactoryDeclaration<KrnI18n, never>;
  static ɵprov: _angular_core.ɵɵInjectableDeclaration<KrnI18n>;
}
/**
 * Replaceable application-wide UI copy. Component-level label inputs remain
 * available for one-off overrides.
 */
declare const KRN_TRANSLATIONS: InjectionToken<Readonly<KrnTranslations>>;

type KrnDirection = 'ltr' | 'rtl';
type KrnMotionPreference = 'system' | 'reduce' | 'full';
type KrnOverlayHost = string | KrnOverlayHostResolver;
interface KrnConfig {
  readonly locale?: string;
  readonly direction?: KrnDirection;
  readonly density?: KrnDensity;
  readonly motion?: KrnMotionPreference;
  readonly theme?: KrnTheme;
  readonly brandColor?: string | null;
  readonly persistPreferences?: boolean;
  readonly preferenceStorageKey?: string;
  readonly overlayHost?: KrnOverlayHost;
  readonly platform?: KrnPlatformAdapter;
  readonly translations?: KrnTranslationsPatch;
}
declare const KRN_CONFIG: InjectionToken<Readonly<KrnConfig>>;
/** Active locale source; read direct injections with `krnReadI18nValue`. */
declare const KRN_LOCALE: InjectionToken<KrnI18nValue<string>>;
declare const KRN_DIRECTION: InjectionToken<KrnDirection>;
declare const KRN_MOTION: InjectionToken<KrnMotionPreference>;
/**
 * Registers Kern's cross-cutting configuration as one environment provider.
 * Feature-level providers may still override individual tokens in a child
 * injector when an embedded application needs a different locale or direction.
 * A child that provides the complete `KRN_TRANSLATIONS` registry directly must
 * also install `provideKrnTranslationBridge()` so dependency-light leaf-copy
 * tokens follow that registry.
 */
declare function provideKrn(config?: KrnConfig): EnvironmentProviders;

/**
 * Immutable date/time seed captured once for an application injector.
 *
 * Server rendering transfers the same reference to the hydrating browser so
 * date-only defaults cannot change with the browser's local time zone during
 * hydration. The seed fields retain server semantics; `todayAt` uses the time
 * zone of the runtime that materialized this token.
 */
interface KrnDateTimeSnapshot {
  /** Epoch milliseconds returned by the configured Kern platform clock. */
  readonly now: number;
  /** Seed IANA time-zone identifier used to derive the transferred `today`. */
  readonly timeZone: string;
  /** Calendar date at `now` in `timeZone`, formatted as `YYYY-MM-DD`. */
  readonly today: string;
  /** Derives a calendar date for a live epoch in the active runtime time zone. */
  readonly todayAt: (now: number) => string;
}
/**
 * The deterministic hydration seed used by date-only controls. Controls derive
 * live client dates through `todayAt` after their first hydrated render.
 * Override this token in a child injector for an explicitly scoped clock.
 */
declare const KRN_DATE_TIME_SNAPSHOT: InjectionToken<Readonly<KrnDateTimeSnapshot>>;

interface KrnLocalePack {
  readonly locale: string;
  readonly direction: KrnDirection;
  readonly translations: Readonly<KrnTranslations>;
}
type KrnLocaleConfig = Readonly<Required<Pick<KrnConfig, 'locale' | 'direction' | 'translations'>>>;
/**
 * Adapts a complete locale pack to `provideKrn` without making consumers copy
 * its locale, direction, and translation fields manually.
 */
declare function krnLocaleConfig(pack: Readonly<KrnLocalePack>): KrnLocaleConfig;
/** Built-in English locale pack. */
declare const KRN_EN_US_LOCALE: Readonly<KrnLocalePack>;
/** Complete built-in Russian locale pack maintained with the public translation schema. */
declare const KRN_RU_RU_LOCALE: Readonly<KrnLocalePack>;
/** Locale packs shipped and schema-checked with KERN. */
declare const KRN_LOCALE_PACKS: Readonly<Record<'en-US' | 'ru-RU', Readonly<KrnLocalePack>>>;

interface KrnThemeConfig {
  readonly theme?: KrnTheme;
  readonly density?: KrnDensity;
  readonly brandColor?: string | null;
  readonly persist?: boolean;
  readonly storageKey?: string;
}
declare const KRN_THEME_CONFIG: InjectionToken<Readonly<KrnThemeConfig>>;
interface KrnPrepaintThemeOptions {
  readonly document?: Document | null;
  readonly storage?: Pick<Storage, 'getItem'> | null;
  readonly storageKey?: string;
  readonly persist?: boolean;
  readonly theme?: KrnTheme;
  readonly density?: KrnDensity;
  readonly brandColor?: string | null;
  readonly systemDark?: boolean;
  readonly forcedContrast?: boolean;
}
interface KrnPrepaintThemeState {
  readonly theme: KrnTheme;
  readonly resolvedTheme: KrnResolvedTheme;
  readonly density: KrnDensity;
  readonly brandColor: string | null;
}
/**
 * Applies validated theme preferences before Angular starts.
 *
 * The helper only mutates attributes and custom properties on an existing
 * document. It never creates inline scripts, uses `eval`, or writes HTML, so it
 * can be called from a CSP-approved external module before `bootstrapApplication`.
 */
declare function applyKrnPrepaintTheme(
  options?: KrnPrepaintThemeOptions,
): KrnPrepaintThemeState | null;
declare class KrnThemeService {
  private readonly config;
  private readonly platform;
  private readonly document;
  private readonly destroyRef;
  private readonly browser;
  private readonly storageKey;
  private readonly systemDark;
  private readonly forcedContrast;
  private readonly initialized;
  private readonly themeState;
  private readonly densityState;
  private readonly brandColorState;
  private documentOwnership;
  readonly theme: _angular_core.Signal<KrnTheme>;
  readonly density: _angular_core.Signal<KrnDensity>;
  readonly brandColor: _angular_core.Signal<string | null>;
  readonly resolvedTheme: _angular_core.Signal<KrnResolvedTheme>;
  resolveTheme(theme: KrnTheme): KrnResolvedTheme;
  constructor();
  initialize(): void;
  setTheme(theme: KrnTheme): void;
  setDensity(density: KrnDensity): void;
  /**
   * Accepts a hexadecimal brand color. Invalid values leave the current brand
   * untouched and return false, making validation easy in theme editors.
   */
  setBrandColor(brandColor: string | null): boolean;
  reset(): void;
  private connectMediaQuery;
  private applyToElement;
  private safeStorage;
  private readPersisted;
  private persist;
  static ɵfac: _angular_core.ɵɵFactoryDeclaration<KrnThemeService, never>;
  static ɵprov: _angular_core.ɵɵInjectableDeclaration<KrnThemeService>;
}
declare function provideKrnTheme(config?: KrnThemeConfig): EnvironmentProviders;
declare class KrnThemeDirective {
  private readonly service;
  private readonly element;
  private readonly renderer;
  private readonly managedBrandProperties;
  readonly theme: _angular_core.InputSignal<KrnTheme | undefined>;
  readonly density: _angular_core.InputSignal<KrnDensity | undefined>;
  readonly brandColor: _angular_core.InputSignal<string | null | undefined>;
  protected readonly themeMode: _angular_core.Signal<KrnTheme>;
  protected readonly resolvedTheme: _angular_core.Signal<KrnResolvedTheme>;
  protected readonly resolvedDensity: _angular_core.Signal<KrnDensity>;
  constructor();
  static ɵfac: _angular_core.ɵɵFactoryDeclaration<KrnThemeDirective, never>;
  static ɵdir: _angular_core.ɵɵDirectiveDeclaration<
    KrnThemeDirective,
    '[krnTheme]',
    never,
    {
      theme: { alias: 'krnTheme'; required: false; isSignal: true };
      density: { alias: 'krnDensity'; required: false; isSignal: true };
      brandColor: { alias: 'krnBrandColor'; required: false; isSignal: true };
    },
    {},
    never,
    never,
    true,
    never
  >;
}

/**
 * Bridges the complete translation registry to the aggregate set of
 * tree-shakable leaf-copy tokens.
 *
 * `provideKrn` installs this automatically. Add it explicitly at a nested
 * injector boundary that provides `KRN_TRANSLATIONS` directly. The returned
 * provider array is intentionally extensible as new leaf-copy tokens appear.
 */
declare function provideKrnTranslationBridge(): Provider[];

export {
  KRN_BRAND_STEPS,
  KRN_BUILT_IN_ICONS,
  KRN_CONFIG,
  KRN_DATE_TIME_SNAPSHOT,
  KRN_DIRECTION,
  KRN_ENGLISH_TRANSLATIONS,
  KRN_EN_US_LOCALE,
  KRN_ICONS,
  KRN_LOCALE,
  KRN_LOCALE_PACKS,
  KRN_MOTION,
  KRN_RU_RU_LOCALE,
  KRN_THEME_CONFIG,
  KRN_TOKEN_MANIFEST,
  KRN_TOKEN_NAMES,
  KRN_TRANSLATIONS,
  KrnI18n,
  KrnIcon,
  KrnIconRegistry,
  KrnThemeDirective,
  KrnThemeService,
  applyKrnPrepaintTheme,
  createKrnTranslations,
  generateKrnBrandPalette,
  krnBrandPaletteVariables,
  krnFormatTranslation,
  krnLocaleConfig,
  krnTokens,
  parseHexColor,
  provideKrn,
  provideKrnIcons,
  provideKrnTheme,
  provideKrnTranslationBridge,
};
export type {
  KrnActionTranslations,
  KrnBrandPalette,
  KrnBrandStep,
  KrnBreakpoint,
  KrnBuiltInIconName,
  KrnCalendarTranslations,
  KrnChartTranslations,
  KrnColorPickerTranslations,
  KrnConfig,
  KrnCssReferenceTree,
  KrnDataDisplayTranslations,
  KrnDataGridTranslations,
  KrnDatePickerTranslations,
  KrnDateTimeSnapshot,
  KrnDensity,
  KrnDirection,
  KrnElevation,
  KrnFeedbackTranslations,
  KrnFormTranslations,
  KrnFoundationSize,
  KrnIconDefinition,
  KrnIconName,
  KrnIconSize,
  KrnLayoutTranslations,
  KrnLocaleConfig,
  KrnLocalePack,
  KrnMotionPreference,
  KrnNavigationTranslations,
  KrnOklchColor,
  KrnOverlayHost,
  KrnPatternTranslations,
  KrnPrepaintThemeOptions,
  KrnPrepaintThemeState,
  KrnRadius,
  KrnResolvedTheme,
  KrnSpace,
  KrnTheme,
  KrnThemeConfig,
  KrnTimePickerTranslations,
  KrnToastTranslations,
  KrnTokenDescriptor,
  KrnTokenName,
  KrnTokenTier,
  KrnTokenTree,
  KrnTokenVisibility,
  KrnTranslations,
  KrnTranslationsPatch,
};
