/**
 * Committed public API baseline for @kern-ui/angular/i18n.
 *
 * Generated by tools/verify-kern-api-baseline.mjs. Update intentionally with
 * `npm run api:baseline:write` and review the declaration diff.
 */

import { Signal, InjectionToken } from '@angular/core';

/** A fixed scoped value or a signal-backed application value. */
type KrnI18nValue<T> = T | Signal<T>;
/** Reads an i18n value while preserving Angular signal dependency tracking. */
declare function krnReadI18nValue<T>(value: KrnI18nValue<T>): T;

/**
 * Small, immutable copy contract for leaf components that must not retain the
 * complete Core translation registry.
 */
interface KrnCopyLabels {
  /** Stable accessible name for the copy action. */
  readonly copy: string;
  /** Polite announcement while an asynchronous write is in flight. */
  readonly copying: string;
  /** Feedback shown and announced after a confirmed write. */
  readonly copied: string;
  /** Feedback shown and announced after a failed write. */
  readonly failed: string;
}
/** English fallback used when an application does not configure copy labels. */
declare const KRN_DEFAULT_COPY_LABELS: Readonly<KrnCopyLabels>;
/**
 * Lightweight application-wide labels for copy actions.
 *
 * `provideKrn({translations})` derives this value from the complete Core
 * translation registry. Consumers that create a nested low-level translation
 * boundary must install `provideKrnTranslationBridge()` or override this token
 * directly. Read the injected fixed-or-signal value with
 * `krnReadI18nValue`.
 */
declare const KRN_COPY_LABELS: InjectionToken<KrnI18nValue<Readonly<KrnCopyLabels>>>;

/** English fallback used when an application does not configure loading copy. */
declare const KRN_DEFAULT_LOADING_LABEL = 'Loading\u2026';
/**
 * Lightweight application-wide loading copy.
 *
 * `provideKrn({translations})` derives this token from
 * `translations.feedback.loadingInProgress`. Consumers that create a nested
 * locale boundary with low-level tokens must also install
 * `provideKrnTranslationBridge()` from Core, or override this leaf token
 * directly. Read the injected fixed-or-signal value with
 * `krnReadI18nValue`.
 */
declare const KRN_LOADING_LABEL: InjectionToken<KrnI18nValue<string>>;

/** Default accessible name for a menu segment that reveals related actions. */
declare const KRN_DEFAULT_MORE_ACTIONS_LABEL = 'More actions';
/**
 * Tree-shakable accessible copy for menu-button segments.
 *
 * `provideKrn` bridges this token to `translations.actions.moreActions`.
 * Leaf consumers can override it directly without retaining the complete
 * translation registry. Read the injected fixed-or-signal value with
 * `krnReadI18nValue`.
 */
declare const KRN_MORE_ACTIONS_LABEL: InjectionToken<KrnI18nValue<string>>;

export {
  KRN_COPY_LABELS,
  KRN_DEFAULT_COPY_LABELS,
  KRN_DEFAULT_LOADING_LABEL,
  KRN_DEFAULT_MORE_ACTIONS_LABEL,
  KRN_LOADING_LABEL,
  KRN_MORE_ACTIONS_LABEL,
  krnReadI18nValue,
};
export type { KrnCopyLabels, KrnI18nValue };
