/**
 * Committed public API baseline for @kern-ui/angular/patterns.
 *
 * Generated by tools/verify-kern-api-baseline.mjs. Update intentionally with
 * `npm run api:baseline:write` and review the declaration diff.
 */

import * as _angular_core from '@angular/core';
import { FormGroup, FormControl } from '@angular/forms';

interface KrnLoginCredentials {
  readonly email: string;
  readonly password: string;
  readonly remember: boolean;
}
interface KrnProfileValue {
  readonly name: string;
  readonly role: string;
  readonly bio: string;
  readonly timezone: string;
}
interface KrnFormStep {
  readonly id: string;
  readonly label: string;
  readonly description?: string;
  readonly optional?: boolean;
  readonly valid?: boolean;
}
declare class KrnLoginForm {
  private readonly translations;
  private readonly instanceId;
  protected readonly emailId: string;
  protected readonly emailErrorId: string;
  protected readonly passwordId: string;
  protected readonly passwordErrorId: string;
  readonly loading: _angular_core.InputSignalWithTransform<boolean, unknown>;
  readonly errorMessage: _angular_core.InputSignal<string>;
  readonly recoveryHref: _angular_core.InputSignal<string>;
  readonly submitLabel: _angular_core.InputSignal<string>;
  readonly emailLabel: _angular_core.InputSignal<string>;
  readonly emailErrorLabel: _angular_core.InputSignal<string>;
  readonly passwordLabel: _angular_core.InputSignal<string>;
  readonly passwordErrorLabel: _angular_core.InputSignal<(minimumLength: number) => string>;
  readonly rememberLabel: _angular_core.InputSignal<string>;
  readonly recoveryLabel: _angular_core.InputSignal<string>;
  readonly loadingLabel: _angular_core.InputSignal<string>;
  readonly minimumPasswordLength: _angular_core.InputSignalWithTransform<number, unknown>;
  readonly submitted: _angular_core.OutputEmitterRef<KrnLoginCredentials>;
  readonly form: FormGroup<{
    email: FormControl<string>;
    password: FormControl<string>;
    remember: FormControl<boolean>;
  }>;
  constructor();
  showError(control: 'email' | 'password'): boolean;
  submit(): void;
  static ɵfac: _angular_core.ɵɵFactoryDeclaration<KrnLoginForm, never>;
  static ɵcmp: _angular_core.ɵɵComponentDeclaration<
    KrnLoginForm,
    'krn-login-form',
    never,
    {
      loading: { alias: 'loading'; required: false; isSignal: true };
      errorMessage: { alias: 'errorMessage'; required: false; isSignal: true };
      recoveryHref: { alias: 'recoveryHref'; required: false; isSignal: true };
      submitLabel: { alias: 'submitLabel'; required: false; isSignal: true };
      emailLabel: { alias: 'emailLabel'; required: false; isSignal: true };
      emailErrorLabel: { alias: 'emailErrorLabel'; required: false; isSignal: true };
      passwordLabel: { alias: 'passwordLabel'; required: false; isSignal: true };
      passwordErrorLabel: { alias: 'passwordErrorLabel'; required: false; isSignal: true };
      rememberLabel: { alias: 'rememberLabel'; required: false; isSignal: true };
      recoveryLabel: { alias: 'recoveryLabel'; required: false; isSignal: true };
      loadingLabel: { alias: 'loadingLabel'; required: false; isSignal: true };
      minimumPasswordLength: { alias: 'minimumPasswordLength'; required: false; isSignal: true };
    },
    { submitted: 'submitted' },
    never,
    never,
    true,
    never
  >;
}
declare class KrnProfileForm {
  private readonly translations;
  private readonly instanceId;
  protected readonly nameId: string;
  protected readonly roleId: string;
  protected readonly bioId: string;
  protected readonly bioCountId: string;
  protected readonly timezoneId: string;
  readonly value: _angular_core.InputSignal<KrnProfileValue>;
  readonly timezones: _angular_core.InputSignal<
    readonly {
      readonly value: string;
      readonly label: string;
    }[]
  >;
  readonly saving: _angular_core.InputSignalWithTransform<boolean, unknown>;
  readonly dirtyMessage: _angular_core.InputSignal<string>;
  readonly nameLabel: _angular_core.InputSignal<string>;
  readonly nameErrorLabel: _angular_core.InputSignal<string>;
  readonly roleLabel: _angular_core.InputSignal<string>;
  readonly bioLabel: _angular_core.InputSignal<string>;
  readonly bioMaxLength: _angular_core.InputSignalWithTransform<number, unknown>;
  readonly timezoneLabel: _angular_core.InputSignal<string>;
  readonly savingLabel: _angular_core.InputSignal<string>;
  readonly saveLabel: _angular_core.InputSignal<string>;
  readonly saved: _angular_core.OutputEmitterRef<KrnProfileValue>;
  readonly form: FormGroup<{
    name: FormControl<string>;
    role: FormControl<string>;
    bio: FormControl<string>;
    timezone: FormControl<string>;
  }>;
  constructor();
  submit(): void;
  static ɵfac: _angular_core.ɵɵFactoryDeclaration<KrnProfileForm, never>;
  static ɵcmp: _angular_core.ɵɵComponentDeclaration<
    KrnProfileForm,
    'krn-profile-form',
    never,
    {
      value: { alias: 'value'; required: false; isSignal: true };
      timezones: { alias: 'timezones'; required: false; isSignal: true };
      saving: { alias: 'saving'; required: false; isSignal: true };
      dirtyMessage: { alias: 'dirtyMessage'; required: false; isSignal: true };
      nameLabel: { alias: 'nameLabel'; required: false; isSignal: true };
      nameErrorLabel: { alias: 'nameErrorLabel'; required: false; isSignal: true };
      roleLabel: { alias: 'roleLabel'; required: false; isSignal: true };
      bioLabel: { alias: 'bioLabel'; required: false; isSignal: true };
      bioMaxLength: { alias: 'bioMaxLength'; required: false; isSignal: true };
      timezoneLabel: { alias: 'timezoneLabel'; required: false; isSignal: true };
      savingLabel: { alias: 'savingLabel'; required: false; isSignal: true };
      saveLabel: { alias: 'saveLabel'; required: false; isSignal: true };
    },
    { saved: 'saved' },
    never,
    never,
    true,
    never
  >;
}
declare class KrnMultiStepForm {
  private readonly ids;
  private readonly translations;
  private readonly instanceId;
  readonly steps: _angular_core.InputSignal<readonly KrnFormStep[]>;
  readonly current: _angular_core.ModelSignal<number>;
  readonly furthestStep: _angular_core.ModelSignal<number>;
  readonly allowStepNavigation: _angular_core.InputSignalWithTransform<boolean, unknown>;
  readonly orientation: _angular_core.InputSignal<'horizontal' | 'vertical'>;
  readonly completeLabel: _angular_core.InputSignal<string>;
  readonly ariaLabel: _angular_core.InputSignal<string>;
  readonly optionalLabel: _angular_core.InputSignal<string>;
  readonly backLabel: _angular_core.InputSignal<string>;
  readonly continueLabel: _angular_core.InputSignal<string>;
  readonly emptyStepLabel: _angular_core.InputSignal<string>;
  readonly stepCounterLabel: _angular_core.InputSignal<(current: number, total: number) => string>;
  readonly completed: _angular_core.OutputEmitterRef<void>;
  protected readonly currentStep: () => KrnFormStep;
  protected readonly currentStepLabelId: () => string;
  goTo(index: number): void;
  next(): void;
  previous(): void;
  static ɵfac: _angular_core.ɵɵFactoryDeclaration<KrnMultiStepForm, never>;
  static ɵcmp: _angular_core.ɵɵComponentDeclaration<
    KrnMultiStepForm,
    'krn-multi-step-form',
    never,
    {
      steps: { alias: 'steps'; required: true; isSignal: true };
      current: { alias: 'current'; required: false; isSignal: true };
      furthestStep: { alias: 'furthestStep'; required: false; isSignal: true };
      allowStepNavigation: { alias: 'allowStepNavigation'; required: false; isSignal: true };
      orientation: { alias: 'orientation'; required: false; isSignal: true };
      completeLabel: { alias: 'completeLabel'; required: false; isSignal: true };
      ariaLabel: { alias: 'ariaLabel'; required: false; isSignal: true };
      optionalLabel: { alias: 'optionalLabel'; required: false; isSignal: true };
      backLabel: { alias: 'backLabel'; required: false; isSignal: true };
      continueLabel: { alias: 'continueLabel'; required: false; isSignal: true };
      emptyStepLabel: { alias: 'emptyStepLabel'; required: false; isSignal: true };
      stepCounterLabel: { alias: 'stepCounterLabel'; required: false; isSignal: true };
    },
    { current: 'currentChange'; furthestStep: 'furthestStepChange'; completed: 'completed' },
    never,
    ['*'],
    true,
    never
  >;
}

interface KrnSearchResult {
  readonly id: string;
  readonly label: string;
  readonly description?: string;
  readonly group?: string;
  readonly keywords?: readonly string[];
}
interface KrnNotification {
  readonly id: string;
  readonly title: string;
  readonly detail: string;
  readonly timestamp: string;
  readonly read: boolean;
  readonly tone?: 'neutral' | 'info' | 'success' | 'warning' | 'danger';
}
interface KrnFilterOption {
  readonly value: string;
  readonly label: string;
  readonly count?: number;
}
interface KrnFilterDefinition {
  readonly id: string;
  readonly label: string;
  readonly options: readonly KrnFilterOption[];
}
declare class KrnUserMenu {
  private readonly platform;
  private readonly translations;
  private readonly host;
  private readonly injector;
  readonly name: _angular_core.InputSignal<string>;
  readonly detail: _angular_core.InputSignal<string>;
  readonly menuAriaLabel: _angular_core.InputSignal<string>;
  readonly open: _angular_core.ModelSignal<boolean>;
  protected toggleMenu(): void;
  protected onTriggerKeydown(event: KeyboardEvent): void;
  protected onMenuKeydown(event: KeyboardEvent): void;
  protected onMenuClick(event: MouseEvent): void;
  protected onFocusOut(event: FocusEvent): void;
  protected closeOnOutsidePointer(event: PointerEvent): void;
  private closeAndFocus;
  private menuItems;
  private focusMenuItem;
  static ɵfac: _angular_core.ɵɵFactoryDeclaration<KrnUserMenu, never>;
  static ɵcmp: _angular_core.ɵɵComponentDeclaration<
    KrnUserMenu,
    'krn-user-menu',
    never,
    {
      name: { alias: 'name'; required: true; isSignal: true };
      detail: { alias: 'detail'; required: false; isSignal: true };
      menuAriaLabel: { alias: 'menuAriaLabel'; required: false; isSignal: true };
      open: { alias: 'open'; required: false; isSignal: true };
    },
    { open: 'openChange' },
    never,
    ['[krnUserAvatar]', '*'],
    true,
    never
  >;
}
declare class KrnNotificationCenter {
  private readonly translations;
  readonly heading: _angular_core.InputSignal<string>;
  readonly ariaLabel: _angular_core.InputSignal<string>;
  readonly unreadLabel: _angular_core.InputSignal<(count: number) => string>;
  readonly unreadStateLabel: _angular_core.InputSignal<string>;
  readonly markAllReadLabel: _angular_core.InputSignal<string>;
  readonly emptyLabel: _angular_core.InputSignal<string>;
  readonly notifications: _angular_core.InputSignal<readonly KrnNotification[]>;
  readonly markAllRead: _angular_core.OutputEmitterRef<void>;
  readonly notificationSelected: _angular_core.OutputEmitterRef<KrnNotification>;
  protected readonly unreadCount: _angular_core.Signal<number>;
  static ɵfac: _angular_core.ɵɵFactoryDeclaration<KrnNotificationCenter, never>;
  static ɵcmp: _angular_core.ɵɵComponentDeclaration<
    KrnNotificationCenter,
    'krn-notification-center',
    never,
    {
      heading: { alias: 'heading'; required: false; isSignal: true };
      ariaLabel: { alias: 'ariaLabel'; required: false; isSignal: true };
      unreadLabel: { alias: 'unreadLabel'; required: false; isSignal: true };
      unreadStateLabel: { alias: 'unreadStateLabel'; required: false; isSignal: true };
      markAllReadLabel: { alias: 'markAllReadLabel'; required: false; isSignal: true };
      emptyLabel: { alias: 'emptyLabel'; required: false; isSignal: true };
      notifications: { alias: 'notifications'; required: false; isSignal: true };
    },
    { markAllRead: 'markAllRead'; notificationSelected: 'notificationSelected' },
    never,
    never,
    true,
    never
  >;
}
declare class KrnGlobalSearch {
  private readonly ids;
  private readonly locale;
  private readonly translations;
  readonly ariaLabel: _angular_core.InputSignal<string>;
  readonly placeholder: _angular_core.InputSignal<string>;
  readonly clearLabel: _angular_core.InputSignal<string>;
  readonly resultsLabel: _angular_core.InputSignal<(label: string) => string>;
  readonly emptyResultsLabel: _angular_core.InputSignal<(query: string) => string>;
  readonly results: _angular_core.InputSignal<readonly KrnSearchResult[]>;
  readonly maxResults: _angular_core.InputSignalWithTransform<number, unknown>;
  readonly resultsId: _angular_core.InputSignal<string>;
  readonly query: _angular_core.ModelSignal<string>;
  readonly open: _angular_core.ModelSignal<boolean>;
  readonly activeIndex: _angular_core.ModelSignal<number>;
  readonly resultSelected: _angular_core.OutputEmitterRef<KrnSearchResult>;
  protected readonly filteredResults: _angular_core.Signal<KrnSearchResult[]>;
  protected readonly activeResultId: _angular_core.Signal<string | null>;
  protected resultOptionId(id: string): string;
  protected onInput(event: Event): void;
  protected onKeydown(event: KeyboardEvent): void;
  protected choose(result: KrnSearchResult): void;
  protected clear(): void;
  static ɵfac: _angular_core.ɵɵFactoryDeclaration<KrnGlobalSearch, never>;
  static ɵcmp: _angular_core.ɵɵComponentDeclaration<
    KrnGlobalSearch,
    'krn-global-search',
    never,
    {
      ariaLabel: { alias: 'ariaLabel'; required: false; isSignal: true };
      placeholder: { alias: 'placeholder'; required: false; isSignal: true };
      clearLabel: { alias: 'clearLabel'; required: false; isSignal: true };
      resultsLabel: { alias: 'resultsLabel'; required: false; isSignal: true };
      emptyResultsLabel: { alias: 'emptyResultsLabel'; required: false; isSignal: true };
      results: { alias: 'results'; required: false; isSignal: true };
      maxResults: { alias: 'maxResults'; required: false; isSignal: true };
      resultsId: { alias: 'resultsId'; required: false; isSignal: true };
      query: { alias: 'query'; required: false; isSignal: true };
      open: { alias: 'open'; required: false; isSignal: true };
      activeIndex: { alias: 'activeIndex'; required: false; isSignal: true };
    },
    {
      query: 'queryChange';
      open: 'openChange';
      activeIndex: 'activeIndexChange';
      resultSelected: 'resultSelected';
    },
    never,
    never,
    true,
    never
  >;
}
declare class KrnFilterBar {
  private readonly translations;
  readonly ariaLabel: _angular_core.InputSignal<string>;
  readonly allLabel: _angular_core.InputSignal<string>;
  readonly activeLabel: _angular_core.InputSignal<(count: number) => string>;
  readonly clearAllLabel: _angular_core.InputSignal<string>;
  readonly filters: _angular_core.InputSignal<readonly KrnFilterDefinition[]>;
  readonly values: _angular_core.ModelSignal<Readonly<Partial<Record<string, string>>>>;
  protected readonly activeCount: _angular_core.Signal<number>;
  protected setFilter(id: string, event: Event): void;
  protected clear(): void;
  static ɵfac: _angular_core.ɵɵFactoryDeclaration<KrnFilterBar, never>;
  static ɵcmp: _angular_core.ɵɵComponentDeclaration<
    KrnFilterBar,
    'krn-filter-bar',
    never,
    {
      ariaLabel: { alias: 'ariaLabel'; required: false; isSignal: true };
      allLabel: { alias: 'allLabel'; required: false; isSignal: true };
      activeLabel: { alias: 'activeLabel'; required: false; isSignal: true };
      clearAllLabel: { alias: 'clearAllLabel'; required: false; isSignal: true };
      filters: { alias: 'filters'; required: false; isSignal: true };
      values: { alias: 'values'; required: false; isSignal: true };
    },
    { values: 'valuesChange' },
    never,
    ['*'],
    true,
    never
  >;
}
declare class KrnPageHeader {
  readonly index: _angular_core.InputSignal<string>;
  readonly eyebrow: _angular_core.InputSignal<string>;
  readonly heading: _angular_core.InputSignal<string>;
  readonly description: _angular_core.InputSignal<string>;
  static ɵfac: _angular_core.ɵɵFactoryDeclaration<KrnPageHeader, never>;
  static ɵcmp: _angular_core.ɵɵComponentDeclaration<
    KrnPageHeader,
    'krn-page-header',
    never,
    {
      index: { alias: 'index'; required: false; isSignal: true };
      eyebrow: { alias: 'eyebrow'; required: false; isSignal: true };
      heading: { alias: 'heading'; required: true; isSignal: true };
      description: { alias: 'description'; required: false; isSignal: true };
    },
    {},
    never,
    ['[krnPageHeaderMeta]', '*'],
    true,
    never
  >;
}
declare class KrnSettingsPanel {
  private readonly translations;
  readonly heading: _angular_core.InputSignal<string>;
  readonly closeLabel: _angular_core.InputSignal<string>;
  readonly open: _angular_core.ModelSignal<boolean>;
  static ɵfac: _angular_core.ɵɵFactoryDeclaration<KrnSettingsPanel, never>;
  static ɵcmp: _angular_core.ɵɵComponentDeclaration<
    KrnSettingsPanel,
    'krn-settings-panel',
    never,
    {
      heading: { alias: 'heading'; required: false; isSignal: true };
      closeLabel: { alias: 'closeLabel'; required: false; isSignal: true };
      open: { alias: 'open'; required: false; isSignal: true };
    },
    { open: 'openChange' },
    never,
    ['*', '[krnSettingsActions]'],
    true,
    never
  >;
}
declare class KrnCrudToolbar {
  private readonly translations;
  readonly ariaLabel: _angular_core.InputSignal<string>;
  readonly selectedCount: _angular_core.InputSignalWithTransform<number, unknown>;
  readonly selectedLabel: _angular_core.InputSignal<(count: number) => string>;
  static ɵfac: _angular_core.ɵɵFactoryDeclaration<KrnCrudToolbar, never>;
  static ɵcmp: _angular_core.ɵɵComponentDeclaration<
    KrnCrudToolbar,
    'krn-crud-toolbar, krn-bulk-actions',
    never,
    {
      ariaLabel: { alias: 'ariaLabel'; required: false; isSignal: true };
      selectedCount: { alias: 'selectedCount'; required: false; isSignal: true };
      selectedLabel: { alias: 'selectedLabel'; required: false; isSignal: true };
    },
    {},
    never,
    ['[krnToolbarTitle]', '*'],
    true,
    never
  >;
}

declare class KrnMasterDetailLayout {
  private readonly translations;
  readonly masterLabel: _angular_core.InputSignal<string>;
  readonly detailLabel: _angular_core.InputSignal<string>;
  readonly detailOpen: _angular_core.ModelSignal<boolean>;
  static ɵfac: _angular_core.ɵɵFactoryDeclaration<KrnMasterDetailLayout, never>;
  static ɵcmp: _angular_core.ɵɵComponentDeclaration<
    KrnMasterDetailLayout,
    'krn-master-detail-layout',
    never,
    {
      masterLabel: { alias: 'masterLabel'; required: false; isSignal: true };
      detailLabel: { alias: 'detailLabel'; required: false; isSignal: true };
      detailOpen: { alias: 'detailOpen'; required: false; isSignal: true };
    },
    { detailOpen: 'detailOpenChange' },
    never,
    ['[krnMaster]', '[krnDetail]'],
    true,
    never
  >;
}
declare class KrnDashboardWidget {
  readonly eyebrow: _angular_core.InputSignal<string>;
  readonly heading: _angular_core.InputSignal<string>;
  static ɵfac: _angular_core.ɵɵFactoryDeclaration<KrnDashboardWidget, never>;
  static ɵcmp: _angular_core.ɵɵComponentDeclaration<
    KrnDashboardWidget,
    'krn-dashboard-widget',
    never,
    {
      eyebrow: { alias: 'eyebrow'; required: false; isSignal: true };
      heading: { alias: 'heading'; required: true; isSignal: true };
    },
    {},
    never,
    ['*', '[krnWidgetFooter]'],
    true,
    never
  >;
}
declare class KrnMobileNavigation {
  private readonly translations;
  readonly ariaLabel: _angular_core.InputSignal<string>;
  static ɵfac: _angular_core.ɵɵFactoryDeclaration<KrnMobileNavigation, never>;
  static ɵcmp: _angular_core.ɵɵComponentDeclaration<
    KrnMobileNavigation,
    'krn-mobile-navigation',
    never,
    { ariaLabel: { alias: 'ariaLabel'; required: false; isSignal: true } },
    {},
    never,
    ['*'],
    true,
    never
  >;
}
declare class KrnResponsiveApplicationShell {
  readonly navigationOpen: _angular_core.ModelSignal<boolean>;
  readonly mainId: _angular_core.InputSignal<string>;
  static ɵfac: _angular_core.ɵɵFactoryDeclaration<KrnResponsiveApplicationShell, never>;
  static ɵcmp: _angular_core.ɵɵComponentDeclaration<
    KrnResponsiveApplicationShell,
    'krn-responsive-application-shell',
    never,
    {
      navigationOpen: { alias: 'navigationOpen'; required: false; isSignal: true };
      mainId: { alias: 'mainId'; required: false; isSignal: true };
    },
    { navigationOpen: 'navigationOpenChange' },
    never,
    ['[krnAppHeader]', '[krnAppNavigation]', '*', '[krnAppMobileNavigation]'],
    true,
    never
  >;
}

export {
  KrnCrudToolbar as KrnBulkActions,
  KrnCrudToolbar as KrnCRUDToolbar,
  KrnCrudToolbar,
  KrnDashboardWidget,
  KrnFilterBar,
  KrnGlobalSearch,
  KrnLoginForm,
  KrnMasterDetailLayout,
  KrnMobileNavigation,
  KrnMultiStepForm,
  KrnNotificationCenter,
  KrnPageHeader,
  KrnProfileForm,
  KrnResponsiveApplicationShell,
  KrnSettingsPanel,
  KrnUserMenu,
};
export type {
  KrnFilterDefinition,
  KrnFilterOption,
  KrnFormStep,
  KrnLoginCredentials,
  KrnNotification,
  KrnProfileValue,
  KrnSearchResult,
};
