/**
 * Committed public API baseline for @kern-ui/angular/testing/layout.
 *
 * Generated by tools/verify-kern-api-baseline.mjs. Update intentionally with
 * `npm run api:baseline:write` and review the declaration diff.
 */

import {
  ComponentHarness,
  BaseHarnessFilters,
  HarnessPredicate,
  TestKey,
} from '@angular/cdk/testing';
import { KrnHarnessText } from '@kern-ui/angular/testing/shared';

interface KrnResizablePanelsHarnessFilters extends BaseHarnessFilters {
  readonly orientation?: 'horizontal' | 'vertical';
  readonly disabled?: boolean;
  readonly resizing?: boolean;
  readonly panelCount?: number;
}
interface KrnResizablePanelHarnessFilters extends BaseHarnessFilters {
  readonly ariaLabel?: KrnHarnessText;
  readonly overflow?: 'auto' | 'visible' | 'clip';
  readonly size?: number;
}
interface KrnResizeHandleHarnessFilters extends BaseHarnessFilters {
  readonly ariaLabel?: KrnHarnessText;
  readonly orientation?: 'horizontal' | 'vertical';
  readonly value?: number;
  readonly disabled?: boolean;
}
/** Harness for `krn-resizable-panel`. */
declare class KrnResizablePanelHarness extends ComponentHarness {
  static readonly hostSelector = 'krn-resizable-panel';
  static with(
    options?: KrnResizablePanelHarnessFilters,
  ): HarnessPredicate<KrnResizablePanelHarness>;
  getId(): Promise<string | null>;
  getAriaLabel(): Promise<string | null>;
  getOverflow(): Promise<'auto' | 'visible' | 'clip' | null>;
  getSize(): Promise<number>;
}
/** Harness for `krn-resize-handle`. */
declare class KrnResizeHandleHarness extends ComponentHarness {
  static readonly hostSelector = 'krn-resize-handle';
  static with(options?: KrnResizeHandleHarnessFilters): HarnessPredicate<KrnResizeHandleHarness>;
  getAriaLabel(): Promise<string | null>;
  getOrientation(): Promise<'horizontal' | 'vertical' | null>;
  getMinimum(): Promise<number | null>;
  getMaximum(): Promise<number | null>;
  getValue(): Promise<number | null>;
  getValueText(): Promise<string | null>;
  isDisabled(): Promise<boolean>;
  sendKeys(...keys: (string | TestKey)[]): Promise<void>;
  moveTowardStart(): Promise<void>;
  moveTowardEnd(): Promise<void>;
  setToMinimum(): Promise<void>;
  setToMaximum(): Promise<void>;
  reset(): Promise<void>;
  focus(): Promise<void>;
  isFocused(): Promise<boolean>;
}
/**
 * Harness for `krn-resizable-panels` and its panels and separator handles.
 *
 * @publicApi
 */
declare class KrnResizablePanelsHarness extends ComponentHarness {
  static readonly hostSelector = 'krn-resizable-panels';
  static with(
    options?: KrnResizablePanelsHarnessFilters,
  ): HarnessPredicate<KrnResizablePanelsHarness>;
  getOrientation(): Promise<'horizontal' | 'vertical' | null>;
  isDisabled(): Promise<boolean>;
  isResizing(): Promise<boolean>;
  getPanels(
    filters?: KrnResizablePanelHarnessFilters,
  ): Promise<readonly KrnResizablePanelHarness[]>;
  getPanelCount(): Promise<number>;
  getSizes(): Promise<readonly number[]>;
  getHandles(filters?: KrnResizeHandleHarnessFilters): Promise<readonly KrnResizeHandleHarness[]>;
}

export { KrnResizablePanelHarness, KrnResizablePanelsHarness, KrnResizeHandleHarness };
export type {
  KrnResizablePanelHarnessFilters,
  KrnResizablePanelsHarnessFilters,
  KrnResizeHandleHarnessFilters,
};
