/**
 * Committed public API baseline for @kern-ui/angular/testing.
 *
 * Generated by tools/verify-kern-api-baseline.mjs. Update intentionally with
 * `npm run api:baseline:write` and review the declaration diff.
 */

import {
  ComponentHarness,
  BaseHarnessFilters,
  HarnessPredicate,
  TestElement,
  ContentContainerComponentHarness,
} from '@angular/cdk/testing';

type KrnHarnessText = string | RegExp;

interface KrnButtonHarnessFilters extends BaseHarnessFilters {
  /** Matches the projected button label. */
  readonly text?: KrnHarnessText;
  /** Matches the accessible label exposed by the native button. */
  readonly ariaLabel?: KrnHarnessText;
  readonly variant?: string;
  readonly tone?: string;
  readonly disabled?: boolean;
  readonly loading?: boolean;
  readonly pressed?: boolean | null;
}
/**
 * Harness for `krn-button`.
 *
 * Consumers should prefer this API over querying KERN's internal DOM or CSS classes.
 *
 * @publicApi
 */
declare class KrnButtonHarness extends ComponentHarness {
  static readonly hostSelector = 'krn-button';
  static with(options?: KrnButtonHarnessFilters): HarnessPredicate<KrnButtonHarness>;
  private readonly button;
  getText(): Promise<string>;
  getAriaLabel(): Promise<string | null>;
  getVariant(): Promise<string | null>;
  getTone(): Promise<string | null>;
  getSize(): Promise<string | null>;
  getType(): Promise<string | null>;
  getName(): Promise<string | null>;
  getValue(): Promise<string>;
  isDisabled(): Promise<boolean>;
  isLoading(): Promise<boolean>;
  isPressed(): Promise<boolean | null>;
  click(): Promise<void>;
  focus(): Promise<void>;
  isFocused(): Promise<boolean>;
  getNativeButton(): Promise<TestElement>;
}

interface KrnDataGridHarnessFilters extends BaseHarnessFilters {
  readonly ariaLabel?: KrnHarnessText;
  readonly loading?: boolean;
  readonly empty?: boolean;
  readonly rowCount?: number;
}
interface KrnDataGridHeaderHarnessFilters extends BaseHarnessFilters {
  readonly text?: KrnHarnessText;
  readonly sortable?: boolean;
}
interface KrnDataGridRowHarnessFilters extends BaseHarnessFilters {
  readonly text?: KrnHarnessText;
  readonly selected?: boolean;
}
/** @publicApi */
declare class KrnDataGridHeaderHarness extends ComponentHarness {
  static readonly hostSelector: string;
  static with(
    options?: KrnDataGridHeaderHarnessFilters,
  ): HarnessPredicate<KrnDataGridHeaderHarness>;
  private readonly sortButton;
  getText(): Promise<string>;
  getSortDirection(): Promise<string | null>;
  isSortable(): Promise<boolean>;
  sort(): Promise<void>;
}
/** @publicApi */
declare class KrnDataGridRowHarness extends ComponentHarness {
  static readonly hostSelector = 'tbody > tr:not(.detail-row), .virtual-row[role="row"]';
  static with(options?: KrnDataGridRowHarnessFilters): HarnessPredicate<KrnDataGridRowHarness>;
  private readonly cells;
  private readonly selection;
  private readonly expansion;
  getText(): Promise<string>;
  getCellTexts(): Promise<readonly string[]>;
  getCellText(columnIndex: number): Promise<string>;
  isSelected(): Promise<boolean>;
  toggleSelection(): Promise<void>;
  toggleExpanded(): Promise<void>;
}
/**
 * Harness for both `krn-data-grid` and its `krn-data-table` alias.
 *
 * @publicApi
 */
declare class KrnDataGridHarness extends ComponentHarness {
  static readonly hostSelector = 'krn-data-grid, krn-data-table';
  static with(options?: KrnDataGridHarnessFilters): HarnessPredicate<KrnDataGridHarness>;
  private readonly shell;
  private readonly filter;
  private readonly resultCount;
  private readonly error;
  private readonly emptyState;
  private readonly headers;
  private readonly rows;
  private readonly selectAll;
  private readonly paginationRange;
  private readonly previousPage;
  private readonly nextPage;
  private readonly virtualGrid;
  getAriaLabel(): Promise<string | null>;
  isLoading(): Promise<boolean>;
  isEmpty(): Promise<boolean>;
  getStateText(): Promise<string | null>;
  getErrorText(): Promise<string | null>;
  getResultCountText(): Promise<string | null>;
  getHeaders(
    filters?: KrnDataGridHeaderHarnessFilters,
  ): Promise<readonly KrnDataGridHeaderHarness[]>;
  getHeaderTexts(): Promise<readonly string[]>;
  getRows(filters?: KrnDataGridRowHarnessFilters): Promise<readonly KrnDataGridRowHarness[]>;
  getRowCount(): Promise<number>;
  getCellText(rowIndex: number, columnIndex: number): Promise<string>;
  setFilter(value: string): Promise<void>;
  getFilterValue(): Promise<string | null>;
  sortByHeader(filters: KrnDataGridHeaderHarnessFilters): Promise<void>;
  toggleSelectAll(): Promise<void>;
  getPaginationRange(): Promise<string | null>;
  goToPreviousPage(): Promise<void>;
  goToNextPage(): Promise<void>;
  isVirtual(): Promise<boolean>;
  getFilterInput(): Promise<TestElement | null>;
}

interface KrnFormControlHarnessFilters extends BaseHarnessFilters {
  readonly value?: KrnHarnessText;
  readonly ariaLabel?: KrnHarnessText;
  readonly placeholder?: KrnHarnessText;
  readonly disabled?: boolean;
  readonly readonly?: boolean;
  readonly required?: boolean;
  readonly invalid?: boolean;
}
/**
 * Harness for KERN's native text-like controls.
 *
 * It covers text, password, search and number inputs as well as textareas while
 * preserving a single interaction contract for consumer tests.
 *
 * @publicApi
 */
declare class KrnFormControlHarness extends ComponentHarness {
  static readonly hostSelector: string;
  static with(options?: KrnFormControlHarnessFilters): HarnessPredicate<KrnFormControlHarness>;
  private readonly control;
  getValue(): Promise<string>;
  setValue(value: string): Promise<void>;
  getId(): Promise<string | null>;
  getAriaLabel(): Promise<string | null>;
  getPlaceholder(): Promise<string | null>;
  getInputType(): Promise<string | null>;
  getDescribedBy(): Promise<readonly string[]>;
  isDisabled(): Promise<boolean>;
  isReadonly(): Promise<boolean>;
  isRequired(): Promise<boolean>;
  isInvalid(): Promise<boolean>;
  focus(): Promise<void>;
  blur(): Promise<void>;
  isFocused(): Promise<boolean>;
  getNativeControl(): Promise<TestElement>;
}

interface KrnFormFieldHarnessFilters extends BaseHarnessFilters {
  readonly label?: KrnHarnessText;
  readonly hint?: KrnHarnessText;
  readonly error?: KrnHarnessText;
  readonly state?: string;
  readonly disabled?: boolean;
  readonly invalid?: boolean;
  readonly required?: boolean;
}
/**
 * Harness for `krn-form-field`, including projected controls and descriptions.
 *
 * @publicApi
 */
declare class KrnFormFieldHarness extends ContentContainerComponentHarness {
  static readonly hostSelector = 'krn-form-field';
  static with(options?: KrnFormFieldHarnessFilters): HarnessPredicate<KrnFormFieldHarness>;
  private readonly label;
  private readonly hints;
  private readonly errors;
  private readonly control;
  getLabelText(): Promise<string | null>;
  getHintTexts(): Promise<readonly string[]>;
  getHintText(): Promise<string | null>;
  getErrorTexts(): Promise<readonly string[]>;
  getErrorText(): Promise<string | null>;
  getState(): Promise<string | null>;
  isDisabled(): Promise<boolean>;
  isInvalid(): Promise<boolean>;
  isRequired(): Promise<boolean>;
  isValid(): Promise<boolean>;
  getControl(): Promise<TestElement | null>;
  getControlId(): Promise<string | null>;
  getControlDescribedBy(): Promise<readonly string[]>;
}

interface KrnOverlayHarnessFilters extends BaseHarnessFilters {
  readonly title?: KrnHarnessText;
  readonly ariaLabel?: KrnHarnessText;
  readonly role?: 'dialog' | 'alertdialog';
  readonly open?: boolean;
}
/**
 * Shared test contract for KERN's modal surfaces.
 *
 * @publicApi
 */
declare abstract class KrnOverlayHarness extends ContentContainerComponentHarness {
  private readonly backdrop;
  private readonly panel;
  private readonly title;
  private readonly description;
  private readonly body;
  private readonly closeButton;
  private readonly actions;
  isOpen(): Promise<boolean>;
  isClosing(): Promise<boolean>;
  getRole(): Promise<string | null>;
  getAriaLabel(): Promise<string | null>;
  getTitleText(): Promise<string | null>;
  getDescriptionText(): Promise<string | null>;
  getBodyText(): Promise<string | null>;
  getPosition(): Promise<string | null>;
  getActionTexts(): Promise<readonly string[]>;
  getActions(): Promise<readonly TestElement[]>;
  getPanel(): Promise<TestElement | null>;
  close(): Promise<void>;
  clickBackdrop(): Promise<void>;
  focus(): Promise<void>;
  isFocused(): Promise<boolean>;
}
declare class KrnDialogHarness extends KrnOverlayHarness {
  static readonly hostSelector = 'krn-dialog';
  static with(options?: KrnOverlayHarnessFilters): HarnessPredicate<KrnDialogHarness>;
}
declare class KrnAlertDialogHarness extends KrnOverlayHarness {
  static readonly hostSelector = 'krn-alert-dialog';
  static with(options?: KrnOverlayHarnessFilters): HarnessPredicate<KrnAlertDialogHarness>;
}
declare class KrnDrawerHarness extends KrnOverlayHarness {
  static readonly hostSelector = 'krn-drawer';
  static with(options?: KrnOverlayHarnessFilters): HarnessPredicate<KrnDrawerHarness>;
}
declare class KrnBottomSheetHarness extends KrnOverlayHarness {
  static readonly hostSelector = 'krn-bottom-sheet';
  static with(options?: KrnOverlayHarnessFilters): HarnessPredicate<KrnBottomSheetHarness>;
}

interface KrnSelectHarnessFilters extends BaseHarnessFilters {
  readonly value?: KrnHarnessText;
  readonly ariaLabel?: KrnHarnessText;
  readonly disabled?: boolean;
  readonly open?: boolean;
  readonly required?: boolean;
  readonly invalid?: boolean;
}
interface KrnSelectOptionHarnessFilters extends BaseHarnessFilters {
  readonly text?: KrnHarnessText;
  readonly disabled?: boolean;
  readonly selected?: boolean;
}
/** @publicApi */
declare class KrnSelectOptionHarness extends ComponentHarness {
  static readonly hostSelector = '.krn-option[role="option"]';
  static with(options?: KrnSelectOptionHarnessFilters): HarnessPredicate<KrnSelectOptionHarness>;
  getText(): Promise<string>;
  isDisabled(): Promise<boolean>;
  isSelected(): Promise<boolean>;
  click(): Promise<void>;
}
/**
 * Harness for `krn-select`.
 *
 * @publicApi
 */
declare class KrnSelectHarness extends ComponentHarness {
  static readonly hostSelector = 'krn-select';
  static with(options?: KrnSelectHarnessFilters): HarnessPredicate<KrnSelectHarness>;
  private readonly trigger;
  private readonly value;
  private readonly placeholder;
  getValueText(): Promise<string | null>;
  getPlaceholderText(): Promise<string | null>;
  getAriaLabel(): Promise<string | null>;
  getId(): Promise<string | null>;
  isOpen(): Promise<boolean>;
  isDisabled(): Promise<boolean>;
  isReadonly(): Promise<boolean>;
  isRequired(): Promise<boolean>;
  isInvalid(): Promise<boolean>;
  open(): Promise<void>;
  close(): Promise<void>;
  getOptions(filters?: KrnSelectOptionHarnessFilters): Promise<readonly KrnSelectOptionHarness[]>;
  getOptionTexts(): Promise<readonly string[]>;
  selectOption(filters: KrnSelectOptionHarnessFilters): Promise<void>;
  focus(): Promise<void>;
  isFocused(): Promise<boolean>;
  getTrigger(): Promise<TestElement>;
}

export {
  KrnAlertDialogHarness,
  KrnBottomSheetHarness,
  KrnButtonHarness,
  KrnDataGridHarness,
  KrnDataGridHeaderHarness,
  KrnDataGridRowHarness,
  KrnDialogHarness,
  KrnDrawerHarness,
  KrnFormControlHarness,
  KrnFormFieldHarness,
  KrnOverlayHarness,
  KrnSelectHarness,
  KrnSelectOptionHarness,
};
export type {
  KrnButtonHarnessFilters,
  KrnDataGridHarnessFilters,
  KrnDataGridHeaderHarnessFilters,
  KrnDataGridRowHarnessFilters,
  KrnFormControlHarnessFilters,
  KrnFormFieldHarnessFilters,
  KrnHarnessText,
  KrnOverlayHarnessFilters,
  KrnSelectHarnessFilters,
  KrnSelectOptionHarnessFilters,
};
