/**
 * Committed public API baseline for @kern-ui/angular/testing/data-display.
 *
 * Generated by tools/verify-kern-api-baseline.mjs. Update intentionally with
 * `npm run api:baseline:write` and review the declaration diff.
 */

import {
  ComponentHarness,
  BaseHarnessFilters,
  HarnessPredicate,
  TestElement,
  TestKey,
} from '@angular/cdk/testing';
import { KrnHarnessText } from '@kern-ui/angular/testing/shared';

interface KrnCalendarCellHarnessFilters extends BaseHarnessFilters {
  readonly date?: string;
  readonly selected?: boolean;
  readonly disabled?: boolean;
}
/** Harness for a calendar grid cell. */
declare class KrnCalendarCellHarness extends ComponentHarness {
  static readonly hostSelector = '[role="gridcell"][data-date]';
  static with(options?: KrnCalendarCellHarnessFilters): HarnessPredicate<KrnCalendarCellHarness>;
  getDate(): Promise<string | null>;
  getLabel(): Promise<string | null>;
  isSelected(): Promise<boolean>;
  isDisabled(): Promise<boolean>;
  click(): Promise<void>;
}
/** Harness for `krn-calendar`. */
declare class KrnCalendarHarness extends ComponentHarness {
  static readonly hostSelector = 'krn-calendar';
  private readonly grid;
  getMonthLabel(): Promise<string | null>;
  getCells(filters?: KrnCalendarCellHarnessFilters): Promise<readonly KrnCalendarCellHarness[]>;
  selectDate(date: string): Promise<void>;
  goToPreviousMonth(): Promise<void>;
  goToNextMonth(): Promise<void>;
}

interface KrnChartHarnessFilters extends BaseHarnessFilters {
  /** Matches the visible chart title. */
  readonly title?: KrnHarnessText;
  readonly type?: 'line' | 'bar' | 'donut';
  readonly empty?: boolean;
  readonly tableVisible?: boolean;
}
interface KrnChartDatumHarnessFilters extends BaseHarnessFilters {
  /** Matches the datum's accessible label. */
  readonly label?: KrnHarnessText;
  readonly active?: boolean;
}
/** Harness for an interactive line point, bar, or donut legend entry. */
declare class KrnChartDatumHarness extends ComponentHarness {
  static readonly hostSelector: string;
  static with(options?: KrnChartDatumHarnessFilters): HarnessPredicate<KrnChartDatumHarness>;
  private readonly legendLabel;
  private readonly legendValue;
  getAccessibleLabel(): Promise<string | null>;
  getValueText(): Promise<string | null>;
  getIndex(): Promise<number | null>;
  isActive(): Promise<boolean>;
  click(): Promise<void>;
  focus(): Promise<void>;
  isFocused(): Promise<boolean>;
  sendKeys(...keys: (string | TestKey)[]): Promise<void>;
}
/** Harness for a row in the optional accessible chart data table. */
declare class KrnChartTableRowHarness extends ComponentHarness {
  static readonly hostSelector = 'tbody > tr';
  private readonly label;
  private readonly cells;
  getLabelText(): Promise<string>;
  getValueText(): Promise<string>;
  getShareText(): Promise<string>;
}
/**
 * Harness for `krn-chart`.
 *
 * The same consumer-facing methods are available on the typed line, bar, and
 * donut wrapper harnesses below.
 *
 * @publicApi
 */
declare class KrnChartHarness extends ComponentHarness {
  static readonly hostSelector: string;
  static with(options?: KrnChartHarnessFilters): HarnessPredicate<KrnChartHarness>;
  private readonly nestedChart;
  private readonly title;
  private readonly description;
  private readonly dataToggle;
  private readonly emptyState;
  private readonly summary;
  private readonly table;
  private readonly tableCaption;
  protected getChartHost(): Promise<TestElement>;
  getType(): Promise<'line' | 'bar' | 'donut' | null>;
  getTitleText(): Promise<string>;
  getDescriptionText(): Promise<string | null>;
  getAccessibleSummary(): Promise<string | null>;
  isEmpty(): Promise<boolean>;
  getEmptyText(): Promise<string | null>;
  isTableVisible(): Promise<boolean>;
  showTable(): Promise<void>;
  hideTable(): Promise<void>;
  getTableCaption(): Promise<string | null>;
  getTableRows(): Promise<readonly KrnChartTableRowHarness[]>;
  getData(filters?: KrnChartDatumHarnessFilters): Promise<readonly KrnChartDatumHarness[]>;
  activateDatum(filters: KrnChartDatumHarnessFilters): Promise<void>;
  getActiveDatum(): Promise<KrnChartDatumHarness | null>;
}
/** Harness for `krn-line-chart`. */
declare class KrnLineChartHarness extends KrnChartHarness {
  static readonly hostSelector: string;
  static with(options?: KrnChartHarnessFilters): HarnessPredicate<KrnLineChartHarness>;
}
/** Harness for `krn-bar-chart`. */
declare class KrnBarChartHarness extends KrnChartHarness {
  static readonly hostSelector: string;
  static with(options?: KrnChartHarnessFilters): HarnessPredicate<KrnBarChartHarness>;
}
/** Harness for `krn-donut-chart`. */
declare class KrnDonutChartHarness extends KrnChartHarness {
  static readonly hostSelector: string;
  static with(options?: KrnChartHarnessFilters): HarnessPredicate<KrnDonutChartHarness>;
}

interface KrnDataGridHarnessFilters extends BaseHarnessFilters {
  readonly ariaLabel?: KrnHarnessText;
  readonly loading?: boolean;
  readonly empty?: boolean;
  readonly rowCount?: number;
}
interface KrnDataGridHeaderHarnessFilters extends BaseHarnessFilters {
  readonly text?: KrnHarnessText;
  readonly sortable?: boolean;
}
interface KrnDataGridRowHarnessFilters extends BaseHarnessFilters {
  readonly text?: KrnHarnessText;
  readonly selected?: boolean;
}
/** @publicApi */
declare class KrnDataGridHeaderHarness extends ComponentHarness {
  static readonly hostSelector: string;
  static with(
    options?: KrnDataGridHeaderHarnessFilters,
  ): HarnessPredicate<KrnDataGridHeaderHarness>;
  private readonly sortButton;
  getText(): Promise<string>;
  getSortDirection(): Promise<string | null>;
  isSortable(): Promise<boolean>;
  sort(): Promise<void>;
}
/** @publicApi */
declare class KrnDataGridRowHarness extends ComponentHarness {
  static readonly hostSelector = 'tbody > tr:not(.detail-row), .virtual-row[role="row"]';
  static with(options?: KrnDataGridRowHarnessFilters): HarnessPredicate<KrnDataGridRowHarness>;
  private readonly cells;
  private readonly selection;
  private readonly expansion;
  getText(): Promise<string>;
  getCellTexts(): Promise<readonly string[]>;
  getCellText(columnIndex: number): Promise<string>;
  isSelected(): Promise<boolean>;
  toggleSelection(): Promise<void>;
  toggleExpanded(): Promise<void>;
}
/**
 * Harness for both `krn-data-grid` and its `krn-data-table` alias.
 *
 * @publicApi
 */
declare class KrnDataGridHarness extends ComponentHarness {
  static readonly hostSelector = 'krn-data-grid, krn-data-table';
  static with(options?: KrnDataGridHarnessFilters): HarnessPredicate<KrnDataGridHarness>;
  private readonly shell;
  private readonly filter;
  private readonly resultCount;
  private readonly error;
  private readonly emptyState;
  private readonly headers;
  private readonly rows;
  private readonly selectAll;
  private readonly paginationRange;
  private readonly previousPage;
  private readonly nextPage;
  private readonly virtualGrid;
  getAriaLabel(): Promise<string | null>;
  isLoading(): Promise<boolean>;
  isEmpty(): Promise<boolean>;
  getStateText(): Promise<string | null>;
  getErrorText(): Promise<string | null>;
  getResultCountText(): Promise<string | null>;
  getHeaders(
    filters?: KrnDataGridHeaderHarnessFilters,
  ): Promise<readonly KrnDataGridHeaderHarness[]>;
  getHeaderTexts(): Promise<readonly string[]>;
  getRows(filters?: KrnDataGridRowHarnessFilters): Promise<readonly KrnDataGridRowHarness[]>;
  getRowCount(): Promise<number>;
  getCellText(rowIndex: number, columnIndex: number): Promise<string>;
  setFilter(value: string): Promise<void>;
  getFilterValue(): Promise<string | null>;
  sortByHeader(filters: KrnDataGridHeaderHarnessFilters): Promise<void>;
  toggleSelectAll(): Promise<void>;
  getPaginationRange(): Promise<string | null>;
  goToPreviousPage(): Promise<void>;
  goToNextPage(): Promise<void>;
  isVirtual(): Promise<boolean>;
  getFilterInput(): Promise<TestElement | null>;
}

interface KrnCompositeItemHarnessFilters extends BaseHarnessFilters {
  readonly text?: KrnHarnessText;
  readonly selected?: boolean;
  readonly disabled?: boolean;
  readonly loading?: boolean;
  readonly error?: boolean;
}
/** Harness for tree and tree-navigation items. */
declare class KrnTreeItemHarness extends ComponentHarness {
  static readonly hostSelector = '[role="treeitem"]';
  static with(options?: KrnCompositeItemHarnessFilters): HarnessPredicate<KrnTreeItemHarness>;
  getText(): Promise<string>;
  getId(): Promise<string | null>;
  getLevel(): Promise<number | null>;
  isExpanded(): Promise<boolean | null>;
  isSelected(): Promise<boolean>;
  isDisabled(): Promise<boolean>;
  isLoading(): Promise<boolean>;
  hasError(): Promise<boolean>;
  click(): Promise<void>;
  expand(): Promise<void>;
  collapse(): Promise<void>;
}
/** Harness for `krn-tree`. */
declare class KrnTreeHarness extends ComponentHarness {
  static readonly hostSelector = 'krn-tree';
  getItems(filters?: KrnCompositeItemHarnessFilters): Promise<readonly KrnTreeItemHarness[]>;
  selectItem(filters: KrnCompositeItemHarnessFilters): Promise<void>;
}

interface KrnJsonNodeHarnessFilters extends BaseHarnessFilters {
  readonly path?: string;
  readonly text?: KrnHarnessText;
  readonly expanded?: boolean;
}
declare class KrnJsonNodeHarness extends ComponentHarness {
  static readonly hostSelector = 'krn-json-view [role="treeitem"]';
  static with(options?: KrnJsonNodeHarnessFilters): HarnessPredicate<KrnJsonNodeHarness>;
  getPath(): Promise<string | null>;
  getText(): Promise<string>;
  isExpanded(): Promise<boolean | null>;
  toggle(): Promise<void>;
}
declare class KrnJsonViewHarness extends ComponentHarness {
  static readonly hostSelector = 'krn-json-view';
  getNodes(filters?: KrnJsonNodeHarnessFilters): Promise<readonly KrnJsonNodeHarness[]>;
}

export {
  KrnBarChartHarness,
  KrnCalendarCellHarness,
  KrnCalendarHarness,
  KrnChartDatumHarness,
  KrnChartHarness,
  KrnChartTableRowHarness,
  KrnDataGridHarness,
  KrnDataGridHeaderHarness,
  KrnDataGridRowHarness,
  KrnDonutChartHarness,
  KrnJsonNodeHarness,
  KrnJsonViewHarness,
  KrnLineChartHarness,
  KrnTreeHarness,
  KrnTreeItemHarness,
};
export type {
  KrnCalendarCellHarnessFilters,
  KrnChartDatumHarnessFilters,
  KrnChartHarnessFilters,
  KrnCompositeItemHarnessFilters,
  KrnDataGridHarnessFilters,
  KrnDataGridHeaderHarnessFilters,
  KrnDataGridRowHarnessFilters,
  KrnJsonNodeHarnessFilters,
};
