/**
 * Committed public API baseline for @kern-ui/angular/testing/shared.
 *
 * Generated by tools/verify-kern-api-baseline.mjs. Update intentionally with
 * `npm run api:baseline:write` and review the declaration diff.
 */

import { TestElement } from '@angular/cdk/testing';

type KrnHarnessText = string | RegExp;
declare function booleanAttributeValue(value: string | null): boolean;
declare function textMatches(
  value: Promise<string | null> | string | null,
  pattern: KrnHarnessText,
): Promise<boolean>;
declare function optionalText(
  element: Promise<TestElement | null>,
  options?: {
    exclude?: string;
  },
): Promise<string | null>;
declare function allText(
  elements: Promise<readonly TestElement[]>,
  options?: {
    exclude?: string;
  },
): Promise<readonly string[]>;
/** Shared predicates used by Kern component harnesses. */
declare const KrnHarnessUtilities: {
  readonly allText: typeof allText;
  readonly booleanAttributeValue: typeof booleanAttributeValue;
  readonly optionalText: typeof optionalText;
  readonly textMatches: typeof textMatches;
};

export { KrnHarnessUtilities };
export type { KrnHarnessText };
