/**
 * Committed public API baseline for @kern-ui/angular/testing/forms.
 *
 * Generated by tools/verify-kern-api-baseline.mjs. Update intentionally with
 * `npm run api:baseline:write` and review the declaration diff.
 */

import {
  ComponentHarness,
  BaseHarnessFilters,
  HarnessPredicate,
  TestElement,
  ComponentHarnessConstructor,
  ContentContainerComponentHarness,
} from '@angular/cdk/testing';
import { KrnHarnessText } from '@kern-ui/angular/testing/shared';
import {
  KrnCalendarCellHarnessFilters,
  KrnCalendarCellHarness,
} from '@kern-ui/angular/testing/data-display';

interface KrnColorPickerHarnessFilters extends BaseHarnessFilters {
  readonly value?: KrnHarnessText;
  readonly ariaLabel?: KrnHarnessText;
  readonly disabled?: boolean;
  readonly readonly?: boolean;
  readonly invalid?: boolean;
  readonly open?: boolean;
}
interface KrnColorPresetHarnessFilters extends BaseHarnessFilters {
  readonly ariaLabel?: KrnHarnessText;
  readonly selected?: boolean;
  readonly disabled?: boolean;
}
/** Harness for a color preset exposed inside `krn-color-picker`. */
declare class KrnColorPresetHarness extends ComponentHarness {
  static readonly hostSelector = '.krn-color-swatches button';
  static with(options?: KrnColorPresetHarnessFilters): HarnessPredicate<KrnColorPresetHarness>;
  getAriaLabel(): Promise<string | null>;
  isSelected(): Promise<boolean>;
  isDisabled(): Promise<boolean>;
  click(): Promise<void>;
}
/**
 * Harness for `krn-color-picker`.
 *
 * @publicApi
 */
declare class KrnColorPickerHarness extends ComponentHarness {
  static readonly hostSelector = 'krn-color-picker';
  static with(options?: KrnColorPickerHarnessFilters): HarnessPredicate<KrnColorPickerHarness>;
  private readonly shell;
  private readonly trigger;
  private readonly triggerValue;
  private readonly textInput;
  private readonly hueInput;
  private readonly saturationInput;
  private readonly lightnessInput;
  private readonly status;
  private readonly doneButton;
  getValueText(): Promise<string>;
  getAriaLabel(): Promise<string | null>;
  isDisabled(): Promise<boolean>;
  isReadonly(): Promise<boolean>;
  isInvalid(): Promise<boolean>;
  isOpen(): Promise<boolean>;
  open(): Promise<void>;
  close(): Promise<void>;
  getPresets(filters?: KrnColorPresetHarnessFilters): Promise<readonly KrnColorPresetHarness[]>;
  selectPreset(filters: KrnColorPresetHarnessFilters): Promise<void>;
  getTextValue(): Promise<string>;
  setValue(value: string): Promise<void>;
  getHue(): Promise<number>;
  setHue(value: number): Promise<void>;
  getSaturation(): Promise<number>;
  setSaturation(value: number): Promise<void>;
  getLightness(): Promise<number>;
  setLightness(value: number): Promise<void>;
  getStatusText(): Promise<string | null>;
  finish(): Promise<void>;
  focus(): Promise<void>;
  isFocused(): Promise<boolean>;
  getTrigger(): Promise<TestElement>;
}

interface KrnPickerHarnessFilters extends BaseHarnessFilters {
  readonly value?: KrnHarnessText;
  readonly ariaLabel?: KrnHarnessText;
  readonly disabled?: boolean;
  readonly open?: boolean;
}
/** Shared harness contract for popup date and time controls. */
declare abstract class KrnPickerHarness extends ComponentHarness {
  protected readonly trigger: () => Promise<TestElement>;
  protected static predicate<T extends KrnPickerHarness>(
    harnessType: ComponentHarnessConstructor<T>,
    options: KrnPickerHarnessFilters,
  ): HarnessPredicate<T>;
  getValueText(): Promise<string>;
  getAriaLabel(): Promise<string | null>;
  isDisabled(): Promise<boolean>;
  isOpen(): Promise<boolean>;
  open(): Promise<void>;
  close(): Promise<void>;
  getTrigger(): Promise<TestElement>;
}
declare abstract class KrnCalendarPickerHarness extends KrnPickerHarness {
  getCells(filters?: KrnCalendarCellHarnessFilters): Promise<readonly KrnCalendarCellHarness[]>;
  selectDate(date: string): Promise<void>;
}
/** Harness for `krn-date-picker`. */
declare class KrnDatePickerHarness extends KrnCalendarPickerHarness {
  static readonly hostSelector = 'krn-date-picker';
  static with(options?: KrnPickerHarnessFilters): HarnessPredicate<KrnDatePickerHarness>;
}
/** Harness for `krn-date-range-picker`. */
declare class KrnDateRangePickerHarness extends KrnCalendarPickerHarness {
  static readonly hostSelector = 'krn-date-range-picker';
  static with(options?: KrnPickerHarnessFilters): HarnessPredicate<KrnDateRangePickerHarness>;
}
/** Harness for `krn-time-picker`. */
declare class KrnTimePickerHarness extends KrnPickerHarness {
  static readonly hostSelector = 'krn-time-picker';
  static with(options?: KrnPickerHarnessFilters): HarnessPredicate<KrnTimePickerHarness>;
  private readonly parts;
  setTime(hour: number, minute: number): Promise<void>;
  getHourInput(): Promise<TestElement>;
}

interface KrnFormControlHarnessFilters extends BaseHarnessFilters {
  readonly value?: KrnHarnessText;
  readonly ariaLabel?: KrnHarnessText;
  readonly placeholder?: KrnHarnessText;
  readonly disabled?: boolean;
  readonly readonly?: boolean;
  readonly required?: boolean;
  readonly invalid?: boolean;
}
/**
 * Harness for KERN's native text-like controls.
 *
 * It covers text, password, search and number inputs as well as textareas while
 * preserving a single interaction contract for consumer tests.
 *
 * @publicApi
 */
declare class KrnFormControlHarness extends ComponentHarness {
  static readonly hostSelector: string;
  static with(options?: KrnFormControlHarnessFilters): HarnessPredicate<KrnFormControlHarness>;
  private readonly control;
  getValue(): Promise<string>;
  setValue(value: string): Promise<void>;
  getId(): Promise<string | null>;
  getAriaLabel(): Promise<string | null>;
  getPlaceholder(): Promise<string | null>;
  getInputType(): Promise<string | null>;
  getDescribedBy(): Promise<readonly string[]>;
  isDisabled(): Promise<boolean>;
  isReadonly(): Promise<boolean>;
  isRequired(): Promise<boolean>;
  isInvalid(): Promise<boolean>;
  focus(): Promise<void>;
  blur(): Promise<void>;
  isFocused(): Promise<boolean>;
  getNativeControl(): Promise<TestElement>;
}

interface KrnFormFieldHarnessFilters extends BaseHarnessFilters {
  readonly label?: KrnHarnessText;
  readonly hint?: KrnHarnessText;
  readonly error?: KrnHarnessText;
  readonly state?: string;
  readonly disabled?: boolean;
  readonly readonly?: boolean;
  readonly invalid?: boolean;
  readonly pending?: boolean;
  readonly required?: boolean;
}
/**
 * Harness for `krn-form-field`, including projected controls and descriptions.
 *
 * @publicApi
 */
declare class KrnFormFieldHarness extends ContentContainerComponentHarness {
  static readonly hostSelector = 'krn-form-field';
  static with(options?: KrnFormFieldHarnessFilters): HarnessPredicate<KrnFormFieldHarness>;
  private readonly label;
  private readonly hints;
  private readonly errors;
  private readonly control;
  getLabelText(): Promise<string | null>;
  getHintTexts(): Promise<readonly string[]>;
  getHintText(): Promise<string | null>;
  getErrorTexts(): Promise<readonly string[]>;
  getErrorText(): Promise<string | null>;
  getState(): Promise<string | null>;
  isDisabled(): Promise<boolean>;
  isReadonly(): Promise<boolean>;
  isInvalid(): Promise<boolean>;
  isPending(): Promise<boolean>;
  isRequired(): Promise<boolean>;
  isValid(): Promise<boolean>;
  getControl(): Promise<TestElement | null>;
  getControlId(): Promise<string | null>;
  getControlDescribedBy(): Promise<readonly string[]>;
}

interface KrnSelectHarnessFilters extends BaseHarnessFilters {
  readonly value?: KrnHarnessText;
  readonly ariaLabel?: KrnHarnessText;
  readonly disabled?: boolean;
  readonly open?: boolean;
  readonly required?: boolean;
  readonly invalid?: boolean;
}
interface KrnSelectOptionHarnessFilters extends BaseHarnessFilters {
  readonly text?: KrnHarnessText;
  readonly disabled?: boolean;
  readonly selected?: boolean;
}
/** @publicApi */
declare class KrnSelectOptionHarness extends ComponentHarness {
  static readonly hostSelector = '.krn-option[role="option"]';
  static with(options?: KrnSelectOptionHarnessFilters): HarnessPredicate<KrnSelectOptionHarness>;
  getText(): Promise<string>;
  isDisabled(): Promise<boolean>;
  isSelected(): Promise<boolean>;
  click(): Promise<void>;
}
/**
 * Harness for `krn-select`.
 *
 * @publicApi
 */
declare class KrnSelectHarness extends ComponentHarness {
  static readonly hostSelector: string;
  static with(options?: KrnSelectHarnessFilters): HarnessPredicate<KrnSelectHarness>;
  private readonly trigger;
  private readonly value;
  private readonly placeholder;
  getValueText(): Promise<string | null>;
  getPlaceholderText(): Promise<string | null>;
  getAriaLabel(): Promise<string | null>;
  getId(): Promise<string | null>;
  isOpen(): Promise<boolean>;
  isDisabled(): Promise<boolean>;
  isReadonly(): Promise<boolean>;
  isRequired(): Promise<boolean>;
  isInvalid(): Promise<boolean>;
  open(): Promise<void>;
  close(): Promise<void>;
  getOptions(filters?: KrnSelectOptionHarnessFilters): Promise<readonly KrnSelectOptionHarness[]>;
  getOptionTexts(): Promise<readonly string[]>;
  selectOption(filters: KrnSelectOptionHarnessFilters): Promise<void>;
  focus(): Promise<void>;
  isFocused(): Promise<boolean>;
  getTrigger(): Promise<TestElement>;
}

interface KrnEditableComboboxHarnessFilters extends BaseHarnessFilters {
  readonly value?: KrnHarnessText;
  readonly ariaLabel?: KrnHarnessText;
  readonly disabled?: boolean;
  readonly open?: boolean;
}
/** Harness for `krn-multi-select`. */
declare class KrnMultiSelectHarness extends KrnSelectHarness {
  static readonly hostSelector: string;
  static with(options?: KrnSelectHarnessFilters): HarnessPredicate<KrnMultiSelectHarness>;
  private readonly tokens;
  getValueText(): Promise<string | null>;
  getVisibleTokenTexts(): Promise<readonly string[]>;
  getSelectedTexts(): Promise<readonly string[]>;
  toggleOption(filters: KrnSelectOptionHarnessFilters): Promise<void>;
}
/** Shared harness contract for editable comboboxes. */
declare abstract class KrnEditableComboboxHarness extends ComponentHarness {
  private readonly input;
  private readonly toggle;
  protected static predicate<T extends KrnEditableComboboxHarness>(
    harnessType: ComponentHarnessConstructor<T>,
    options: KrnEditableComboboxHarnessFilters,
  ): HarnessPredicate<T>;
  getValue(): Promise<string | null>;
  getAriaLabel(): Promise<string | null>;
  isDisabled(): Promise<boolean>;
  isReadonly(): Promise<boolean>;
  isOpen(): Promise<boolean>;
  setValue(value: string): Promise<void>;
  open(): Promise<void>;
  close(): Promise<void>;
  getOptions(filters?: KrnSelectOptionHarnessFilters): Promise<readonly KrnSelectOptionHarness[]>;
  selectOption(filters: KrnSelectOptionHarnessFilters): Promise<void>;
  getInput(): Promise<TestElement>;
  getPlaceholder(): Promise<string | null>;
}
/** Harness for constrained `krn-combobox`. */
declare class KrnComboboxHarness extends KrnEditableComboboxHarness {
  static readonly hostSelector = 'krn-combobox';
  static with(options?: KrnEditableComboboxHarnessFilters): HarnessPredicate<KrnComboboxHarness>;
}
/** Harness for free-text `krn-autocomplete`. */
declare class KrnAutocompleteHarness extends KrnEditableComboboxHarness {
  static readonly hostSelector = 'krn-autocomplete';
  static with(
    options?: KrnEditableComboboxHarnessFilters,
  ): HarnessPredicate<KrnAutocompleteHarness>;
}

interface KrnFileUploadHarnessFilters extends BaseHarnessFilters {
  readonly label?: KrnHarnessText;
  readonly accept?: KrnHarnessText;
  readonly multiple?: boolean;
  readonly disabled?: boolean;
  readonly readonly?: boolean;
}
interface KrnDropUploadHarnessFilters extends KrnFileUploadHarnessFilters {
  readonly dropLabel?: KrnHarnessText;
}
/** Shared harness contract for file upload controls. */
declare abstract class KrnUploadHarness extends ComponentHarness {
  private readonly root;
  private readonly input;
  private readonly button;
  private readonly files;
  getLabel(): Promise<string>;
  getAccept(): Promise<string | null>;
  isMultiple(): Promise<boolean>;
  isDisabled(): Promise<boolean>;
  isReadonly(): Promise<boolean>;
  getFileNames(): Promise<readonly string[]>;
  removeFile(index?: number): Promise<void>;
  getNativeInput(): Promise<TestElement>;
  focus(): Promise<void>;
  isFocused(): Promise<boolean>;
}
/** Harness for `krn-file-upload`. */
declare class KrnFileUploadHarness extends KrnUploadHarness {
  static readonly hostSelector = 'krn-file-upload';
  static with(options?: KrnFileUploadHarnessFilters): HarnessPredicate<KrnFileUploadHarness>;
}
/** Harness for `krn-drop-upload` and its documented alias. */
declare class KrnDropUploadHarness extends KrnUploadHarness {
  static readonly hostSelector = 'krn-drop-upload, krn-drag-drop-upload';
  static with(options?: KrnDropUploadHarnessFilters): HarnessPredicate<KrnDropUploadHarness>;
  getDropLabel(): Promise<string>;
}

export {
  KrnAutocompleteHarness,
  KrnColorPickerHarness,
  KrnColorPresetHarness,
  KrnComboboxHarness,
  KrnDatePickerHarness,
  KrnDateRangePickerHarness,
  KrnDropUploadHarness,
  KrnEditableComboboxHarness,
  KrnFileUploadHarness,
  KrnFormControlHarness,
  KrnFormFieldHarness,
  KrnMultiSelectHarness,
  KrnPickerHarness,
  KrnSelectHarness,
  KrnSelectOptionHarness,
  KrnTimePickerHarness,
  KrnUploadHarness,
};
export type {
  KrnColorPickerHarnessFilters,
  KrnColorPresetHarnessFilters,
  KrnDropUploadHarnessFilters,
  KrnEditableComboboxHarnessFilters,
  KrnFileUploadHarnessFilters,
  KrnFormControlHarnessFilters,
  KrnFormFieldHarnessFilters,
  KrnPickerHarnessFilters,
  KrnSelectHarnessFilters,
  KrnSelectOptionHarnessFilters,
};
