/**
 * Committed public API baseline for @kern-ui/angular/testing/navigation.
 *
 * Generated by tools/verify-kern-api-baseline.mjs. Update intentionally with
 * `npm run api:baseline:write` and review the declaration diff.
 */

import {
  ComponentHarness,
  BaseHarnessFilters,
  HarnessPredicate,
  TestKey,
  TestElement,
} from '@angular/cdk/testing';
import { KrnHarnessText } from '@kern-ui/angular/testing/shared';
import {
  KrnCompositeItemHarnessFilters,
  KrnTreeItemHarness,
} from '@kern-ui/angular/testing/data-display';

interface KrnCommandPaletteHarnessFilters extends BaseHarnessFilters {
  readonly title?: KrnHarnessText;
  readonly query?: KrnHarnessText;
  readonly open?: boolean;
  readonly resultCount?: number;
}
interface KrnCommandPaletteOptionHarnessFilters extends BaseHarnessFilters {
  readonly label?: KrnHarnessText;
  readonly selected?: boolean;
}
/** Harness for a command-palette result option. */
declare class KrnCommandPaletteOptionHarness extends ComponentHarness {
  static readonly hostSelector = '[role="listbox"] > [role="option"]';
  static with(
    options?: KrnCommandPaletteOptionHarnessFilters,
  ): HarnessPredicate<KrnCommandPaletteOptionHarness>;
  private readonly label;
  private readonly description;
  private readonly shortcut;
  getId(): Promise<string | null>;
  getLabelText(): Promise<string>;
  getDescriptionText(): Promise<string | null>;
  getShortcutText(): Promise<string | null>;
  isSelected(): Promise<boolean>;
  click(): Promise<void>;
}
/**
 * Harness for `krn-command-palette`.
 *
 * Opening the palette remains an application concern because the component has
 * no visual trigger of its own. Once open, this harness owns all palette
 * interactions.
 *
 * @publicApi
 */
declare class KrnCommandPaletteHarness extends ComponentHarness {
  static readonly hostSelector = 'krn-command-palette';
  static with(
    options?: KrnCommandPaletteHarnessFilters,
  ): HarnessPredicate<KrnCommandPaletteHarness>;
  private readonly dialog;
  private readonly title;
  private readonly description;
  private readonly search;
  private readonly empty;
  isOpen(): Promise<boolean>;
  getTitleText(): Promise<string | null>;
  getDescriptionText(): Promise<string | null>;
  getQuery(): Promise<string | null>;
  getPlaceholder(): Promise<string | null>;
  setQuery(value: string): Promise<void>;
  getOptions(
    filters?: KrnCommandPaletteOptionHarnessFilters,
  ): Promise<readonly KrnCommandPaletteOptionHarness[]>;
  getResultCount(): Promise<number>;
  getResultLabels(): Promise<readonly string[]>;
  getActiveOption(): Promise<KrnCommandPaletteOptionHarness | null>;
  selectOption(filters: KrnCommandPaletteOptionHarnessFilters): Promise<void>;
  getEmptyText(): Promise<string | null>;
  sendKeys(...keys: (string | TestKey)[]): Promise<void>;
  close(): Promise<void>;
  getSearchInput(): Promise<TestElement>;
  private requireSearch;
}

/** Harness for `krn-tree-navigation`. */
declare class KrnTreeNavigationHarness extends ComponentHarness {
  static readonly hostSelector = 'krn-tree-navigation';
  getItems(filters?: KrnCompositeItemHarnessFilters): Promise<readonly KrnTreeItemHarness[]>;
  selectItem(filters: KrnCompositeItemHarnessFilters): Promise<void>;
}
/** Harness for `krn-menu`. */
declare class KrnMenuHarness extends ComponentHarness {
  static readonly hostSelector = 'krn-menu';
  private readonly trigger;
  isOpen(): Promise<boolean>;
  open(): Promise<void>;
  close(): Promise<void>;
  getItemTexts(): Promise<readonly string[]>;
  clickItem(text: KrnHarnessText): Promise<void>;
}
/** Harness for `krn-tabs` and `krn-vertical-tabs`. */
declare class KrnTabsHarness extends ComponentHarness {
  static readonly hostSelector = 'krn-tabs, krn-vertical-tabs';
  private readonly tabs;
  getTabTexts(): Promise<readonly string[]>;
  getSelectedTabText(): Promise<string | null>;
  selectTab(text: KrnHarnessText): Promise<void>;
}

export {
  KrnCommandPaletteHarness,
  KrnCommandPaletteOptionHarness,
  KrnMenuHarness,
  KrnTabsHarness,
  KrnTreeNavigationHarness,
};
export type { KrnCommandPaletteHarnessFilters, KrnCommandPaletteOptionHarnessFilters };
