/**
 * Committed public API baseline for @kern-ui/angular/testing/feedback.
 *
 * Generated by tools/verify-kern-api-baseline.mjs. Update intentionally with
 * `npm run api:baseline:write` and review the declaration diff.
 */

import {
  ContentContainerComponentHarness,
  TestElement,
  BaseHarnessFilters,
  HarnessPredicate,
  ComponentHarness,
} from '@angular/cdk/testing';
import { KrnHarnessText } from '@kern-ui/angular/testing/shared';

interface KrnOverlayHarnessFilters extends BaseHarnessFilters {
  readonly title?: KrnHarnessText;
  readonly ariaLabel?: KrnHarnessText;
  readonly role?: 'dialog' | 'alertdialog';
  readonly open?: boolean;
}
/**
 * Shared test contract for KERN's modal surfaces.
 *
 * @publicApi
 */
declare abstract class KrnOverlayHarness extends ContentContainerComponentHarness {
  private readonly backdrop;
  private readonly panel;
  private readonly title;
  private readonly description;
  private readonly body;
  private readonly closeButton;
  private readonly actions;
  isOpen(): Promise<boolean>;
  isClosing(): Promise<boolean>;
  getRole(): Promise<string | null>;
  getAriaLabel(): Promise<string | null>;
  getTitleText(): Promise<string | null>;
  getDescriptionText(): Promise<string | null>;
  getBodyText(): Promise<string | null>;
  getPosition(): Promise<string | null>;
  getActionTexts(): Promise<readonly string[]>;
  getActions(): Promise<readonly TestElement[]>;
  getPanel(): Promise<TestElement | null>;
  close(): Promise<void>;
  clickBackdrop(): Promise<void>;
  focus(): Promise<void>;
  isFocused(): Promise<boolean>;
}
declare class KrnDialogHarness extends KrnOverlayHarness {
  static readonly hostSelector = 'krn-dialog';
  static with(options?: KrnOverlayHarnessFilters): HarnessPredicate<KrnDialogHarness>;
}
declare class KrnAlertDialogHarness extends KrnOverlayHarness {
  static readonly hostSelector = 'krn-alert-dialog';
  static with(options?: KrnOverlayHarnessFilters): HarnessPredicate<KrnAlertDialogHarness>;
}
declare class KrnDrawerHarness extends KrnOverlayHarness {
  static readonly hostSelector = 'krn-drawer';
  static with(options?: KrnOverlayHarnessFilters): HarnessPredicate<KrnDrawerHarness>;
}
declare class KrnBottomSheetHarness extends KrnOverlayHarness {
  static readonly hostSelector = 'krn-bottom-sheet';
  static with(options?: KrnOverlayHarnessFilters): HarnessPredicate<KrnBottomSheetHarness>;
}

/** Harness for `krn-toast-viewport`. */
declare class KrnToastViewportHarness extends ComponentHarness {
  static readonly hostSelector = 'krn-toast, krn-toast-viewport, krn-snackbar';
  private readonly toasts;
  private readonly messages;
  getMessages(): Promise<readonly string[]>;
  getCount(): Promise<number>;
  dismiss(index?: number): Promise<void>;
  clearAll(): Promise<void>;
}

export {
  KrnAlertDialogHarness,
  KrnBottomSheetHarness,
  KrnDialogHarness,
  KrnDrawerHarness,
  KrnOverlayHarness,
  KrnToastViewportHarness,
};
export type { KrnOverlayHarnessFilters };
